(function(b){b.fn.xBreadcrumbs=function(c){function d(){f.children("LI").children("UL").each(function(){b(this).hide();b(this).parent().removeClass("hover")})}function a(a,f){f?(a.parent().addClass("hover"),b.browser.msie&&a.parent().position(),c.showSpeed!=""?a.fadeIn(c.showSpeed):a.show()):(a.parent().removeClass("hover"),c.hideSpeed!=""?a.fadeOut(c.hideSpeed):a.hide())}var f=b(this),c=b.extend({},b.fn.xBreadcrumbs.defaults,c);(function(){if(c.collapsible){var e=f.children("LI").length;f.children("LI").children("A").css("white-space",
"nowrap").css("float","left");f.children("LI").children("A").each(function(a){a!=e-1&&(b(this).css("overflow","hidden"),b(this).attr("init-width",b(this).width()),b(this).width(c.collapsedWidth))})}f.children("LI").mouseenter(function(){if(!b(this).hasClass("hover")&&(d(),b(this).children("UL").length>0)){var f=b(this).children("UL");f.length&&window==top&&b.isOcx&&b.isOcx.needModal()&&b.isOcx.createModal(document.getElementById("mainFrame").contentWindow);a(f,!0);b.fn.bgiframe&&b(f).bgiframe();c.collapsible&&
!b(this).hasClass("current")&&(f=b(this).children("A").attr("init-width"),b(this).children("A").animate({width:f},"normal"))}});f.children("LI").mouseleave(function(){var f=b(this).children("UL");f.length&&window==top&&b.isOcx&&b.isOcx.needModal()&&b.isOcx.removeModal(document.getElementById("mainFrame").contentWindow);a(f,!1);c.collapsible&&!b(this).hasClass("current")&&b(this).children("A").animate({width:c.collapsedWidth},"fast")})})()};b.fn.xBreadcrumbs.defaults={showSpeed:"fast",hideSpeed:"",
collapsible:!1,collapsedWidth:10}})(jQuery);
(function(b,c,d){function a(){h=c[g](function(){f.each(function(){var a=b(this),c=a.width(),f=a.height(),e=b.data(this,j);if(c!==e.w||f!==e.h)a.trigger(i,[e.w=c,e.h=f])});a()},e[m])}var f=b([]),e=b.resize=b.extend(b.resize,{}),h,g="setTimeout",i="resize",j=i+"-special-event",m="delay";e[m]=250;e.throttleWindow=!0;b.event.special[i]={setup:function(){if(!e.throttleWindow&&this[g])return!1;var c=b(this);f=f.add(c);b.data(this,j,{w:c.width(),h:c.height()});f.length===1&&a()},teardown:function(){if(!e.throttleWindow&&
this[g])return!1;var a=b(this);f=f.not(a);a.removeData(j);f.length||clearTimeout(h)},add:function(a){function c(a,e,h){var g=b(this),m=b.data(this,j);m.w=e!==d?e:g.width();m.h=h!==d?h:g.height();f.apply(this,arguments)}if(!e.throttleWindow&&this[g])return!1;var f;if(b.isFunction(a))return f=a,c;else f=a.handler,a.handler=c}}})(jQuery,this);
(function(b,c){var d={buttons:!0,height:!0,maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0,width:!0};b._fixIframe=function(a){b("<iframe id='blankIframe' name='blankIframe' style='position:absolute;z-index:-1;filter:alpha(opacity=0);' frameborder='no' border='0' "+(/msie 8/i.test(navigator.userAgent)?"src='javascript:false;'":"")+"></iframe>").css({width:/msie 6/i.test(navigator.userAgent)?a.css("width"):"100%",height:/msie 6/i.test(navigator.userAgent)?a.css("height"):"100%",top:0,left:0}).appendTo(a)};
b.widget("hk.pop",{options:{popClass:"pop",modal:!0,overlayTrans:0.5,overlayClass:"pop_overlay",wrap:null,content:null,leaveClose:!1,position:{my:"center",at:"center",of:window,collision:"fit",using:function(a){var c=b(this).css(a).offset().top;c<0&&b(this).css("top",a.top-c)}},closeDestroy:!1,leaveclose:!1,leavecloseTM:200,reserve:!0,width:500,height:"auto",minHeight:150,iframeFix:!0,show:"fade",stack:!0,zIndex:1E3,autoOpen:!0,draggable:!1,dragHandle:".popTitle"},_create:function(){this.initPopup()},
initPopup:function(){var a=this.options,c=this.element,e;this.oldPosition={parent:this.element.parent(),index:this.element.parent().children().index(this.element)};this.wrap=e=(this.wrap||b("<div>")).attr("tabIndex",-1).appendTo("body").addClass(a.popClass).addClass(a.type).css({display:"none",zIndex:a.zIndex,"box-sizing":"border-box"});this.content=(this.content||e).append(c.show());this.wrap.css({width:a.width,height:a.height});a.draggable&&b.fn.draggable&&this.drag();a.iframeFix&&!a.modal&&b._fixIframe(this.wrap);
this.bindEvent();this._isOpen=!1;this.element.data("pop")||this.element.data("pop",this.element.data(this.widgetName))},widget:function(){return this.wrap},_init:function(){this.options.autoOpen&&this.open()},drag:function(){function a(a){return{position:a.position,offset:a.offset}}var c=this,e=this.options;this.wrap.draggable({handle:this.options.dragHandle,iframeFix:this.options.iframeFix,containment:"document",start:function(e,d){b(this).addClass("pop-dragging");c._trigger("dragStart",e,a(d))},
drag:function(b,e){c._trigger("drag",b,a(e))},stop:function(d,g){e.position=[g.position.left-c.document.scrollLeft(),g.position.top-c.document.scrollTop()];b(this).removeClass("pop-dragging");c._trigger("dragStop",d,a(g))}})},_position:function(a){var c={of:window,collision:this.options.positionCollision};b.isPlainObject(a)?a=b.extend(c,a):b.isArray(a)?typeof a[0]=="string"&&typeof a[1]=="string"?(a=a.join(" "),a=b.extend(c,{my:a,at:a})):a=a[0].constructor==Number&&a[1].constructor==Number?b.extend(c,
{of:document,my:"left top",at:"left top",offset:a[0]+" "+a[1]}):["center","center"]:typeof a==="string"?/-/.test(a)&&(a=a.split("-"),a=/top|bottom/.test(a[0])||/left|right/.test(a[1])?b.extend(c,{my:a[1]+" "+a[0],at:a[1]+" "+a[0]}):b.extend(c,{my:a[0]+" "+a[1],at:a[0]+" "+a[1]})):a=["center","center"];b.isPlainObject(a)&&((c=this.wrap.is(":visible"))||this.wrap.show(),this.wrap.css({top:0,left:0}).position(a),c||this.wrap.hide())},_close:function(a){var c,e=this,d;if(this._isOpen){var g=this.options;
if(this._trigger("beforeClose",a,this.wrap)===!1)return!1;this.modal&&b.overlay.destroy(this.modal);c=0;b(".popWrap").each(function(){this!==e.wrap[0]&&(d=b(this).css("z-index"),isNaN(d)||(c=Math.max(c,d)))});b.hk.pop.maxZ=c;a=b.isFunction(a)?a:function(){};this.wrap.hide();a();try{g.afterclose&&g.afterclose()}catch(i){}this._isOpen=!1;this._trigger("close")}},close:function(){this.clearCloseTM();window==top&&b.isOcx&&b.isOcx.needModal()&&document.getElementById("mainFrame")&&document.getElementById("mainFrame")&&
b.isOcx.removeModal(document.getElementById("mainFrame").contentWindow);if(this.options.closeDestroy)return this.destroy();this._close()},destroy:function(){for(var a=this,c=this.options,e=0,d=openPopWinOptList.length;e<d;e++)c.msg==openPopWinOptList[e].msg&&c.level==openPopWinOptList[e].level&&c.title==openPopWinOptList[e].title&&openPopWinOptList.splice(e,1);this._close(function(){b.Widget.prototype.destroy.apply(a,arguments);/msie 8/i.test(navigator.userAgent)&&a.wrap.find("iframe").not("#blankIframe").attr("src",
"about:_blank");a.wrap.remove()})},_destroy:function(){var a,c=this.oldPosition;this.originalTitle&&this.element.attr("title",this.originalTitle);!this.options.iframeSrc&&!this.options.ajax&&!this.options.closeDestroy&&(this.element.hide().appendTo("body"),a=c.parent.children().eq(c.index),a.length&&a[0]!==this.element[0]?a.before(this.element):c.parent.append(this.element))},clearCloseTM:function(){clearTimeout(this.leaveTM);this.leaveTM=null},open:function(){var a=this.options,c=this,e;if(!this._isOpen){if(a.autoclose)this.wrap.one("mousemove.pop",
function(){c.clearCloseTM();c.wrap.one("mouseleave.pop",function(){c.leaveTM=setTimeout(function(){c.close()},a.autoclose)})});this._size();this._position(a.position);this.show();this.modal=a.modal&&openPopWinOptList.length==0?b.overlay.create(a):null;this.moveToTop(!0);e=this.element.find(":tabbable");if(!e.length&&(e=this.element.find(":tabbable"),!e.length))e=this.wrap;e.eq(0).focus()}},_size:function(){var a=this.options,c,e;this.element.show().css({width:"auto",minHeight:0,height:0});c=this.wrap.css({height:"auto",
width:a.width}).outerHeight();e=Math.max(0,a.minHeight-c);a.height==="auto"?b.support.minHeight?this.element.css({minHeight:e,height:"auto"}):(this.wrap.show(),a=this.element.css("height","auto").height(),this.element.height(Math.max(a,e))):this.element.height(Math.max(a.height-c,0))},show:function(){var a=this.options,c=this,e;e=function(){c._isOpen=!0;c._trigger("open",c.wrap,c)};window==top&&b.isOcx&&b.isOcx.needModal()&&document.getElementById("mainFrame")&&document.getElementById("mainFrame")&&
b.isOcx.createModal(document.getElementById("mainFrame").contentWindow);/msie 8|7|6/i.test(navigator.userAgent)?(this.wrap.show(),e()):b.effects&&((isObj=b.isPlainObject(a.show))||typeof a.show==="string")?isObj?this.wrap.show(a.show.effect||"fade",a.show,a.show.duration||500,e):this.wrap.show(a.show,{},500,e):(this.wrap.show(),e())},moveToTop:function(a,c){var e=this.options;if(e.modal&&!a||!e.stack&&!e.modal)return this._trigger("focus",c);if(e.zIndex>b.hk.pop.maxZ)b.hk.pop.maxZ=e.zIndex;this.modal&&
(b.hk.pop.maxZ+=1,this.modal.css("z-index",b.hk.pop.maxZ));e={scrollTop:this.element.scrollTop(),scrollLeft:this.element.scrollLeft()};b.hk.pop.maxZ+=1;this.wrap.css("z-index",b.hk.pop.maxZ);this.element.attr(e);this._trigger("focus",c);return this},bindEvent:function(){var a=this;this.wrap.on("click","[close],[data-close]",function(){a.close();return!1})}});b.overlay={instances:[],create:function(a){var c=this,e;this.instances.length===0&&b(window).bind("resize.overlay",function(){c.resize()});e=
b("<div></div>").appendTo("body").addClass(a.overlayClass).css({width:c.width(),height:c.height(),zIndex:a.zIndex-1});this.fixOverlayTrans(e,a);a.iframeFix&&b._fixIframe(e);this.instances.push(e);return e},fixOverlayTrans:function(a,c){c.overlayTrans!==1&&/msie 8/i.test(navigator.userAgent)?a.css("filter","alpha(opacity="+c.overlayTrans*100+")"):a.css("opacity",c.overlayTrans)},destroy:function(a){this.instances.splice(b.inArray(this.instances,a),1);this.instances.length===0&&b(window).unbind(".overlay");
a.remove()},height:function(){var a=document,c=a.body,a=a.documentElement;return Math.max(Math.max(c.scrollHeight,a.scrollHeight),Math.max(c.clientHeight,a.clientHeight))},width:function(){var a=document,c=a.body,a=a.documentElement;return Math.max(Math.max(c.scrollWidth,a.scrollWidth),Math.max(c.clientWidth,a.clientWidth))},resize:function(){var a=this;b.each(this.instances,function(){b(this).css({width:0,height:0}).css({width:a.width(),height:a.height()})})}};b.extend(b.hk.pop,{uuid:0,maxZ:0});
b.widget("hk.popWin",b.hk.pop,{options:{popClass:"popWin",modal:!0,overlayTrans:0.25,closeText:"close",closeButton:!0,title:"",draggable:!1,buttonDefaultClass:"buttonM bDefault",buttons:[]},_create:function(){var a=this.options,c,b;this.wrap||this.createHTML();this._createButtons(a.buttons);c=this.wrap.find(".popTitle h3");b=this.wrap.find(".popClose");c.html(a.title||this.element.attr("title"));a.closeButton?b.html(a.closeText):b.hide();!a.title&&!a.closeButton&&c.parent().hide();this._super()},
_createButtons:function(a){var c=this;this.button.empty();b.isArray(a)&&a.length>0||typeof a==="object"&&a!==null?b.each(a,function(a,d){var g=c.options.maybeRefresh,i,d=b.isFunction(d)?{click:d,text:a}:d,d=b.extend({type:"button"},d);i=g?d.click.toString():d.click;var j=c.options.id==null?window:window.frames[c.options.id],j=j||window;if(j.$&&(j=j.$,j.callback))j=j.callback;d.click=typeof i==="string"?function(){var a=new c.options.originalPage.Function("return ("+i+").apply(this, arguments)");try{a.call(c,
c,j,c.element[0])}catch(b){}}:function(){i.call(c,c,j,c.element[0])};b("<button></button>",d).appendTo(c.button)}):this.button.hide()},_setOptions:function(a){var c=this,e=!1;b.each(a,function(a,b){c._setOption(a,b);a in d&&(e=!0)});e&&this._size();this.wrap.is(":data(resizable)")},_setOption:function(a,c){var b=this.wrap;switch(a){case "buttons":this._createButtons(c);break;case "disabled":c?b.addClass("ui-dialog-disabled"):b.removeClass("ui-dialog-disabled");break;case "position":this._position(c);
break;case "title":this.wrap.find(".popTitle h3").html(""+(c||"&#160;"))}this._super(a,c)},createHTML:function(){this.wrap=b(this.popWinTeml());this.content=this.wrap.find(".popContent");this.button=this.wrap.find(".popButton")},popWinTeml:function(){var a=this.options.dialogClass!==c?this.options.dialogClass:"",b=/msie 8/i.test(navigator.userAgent)&&this.options.modal?"":'style="border: 1px solid #e4e4e4; -moz-border-radius: 3px; -webkit-border-radius: 3px; border-radius: 3px;"';return'<div class="popWrap '+
a+'" '+b+'><div class="popInner"><div class="popTitle"><a class="popClose" href="javascript:void(0)" close></a><h3></h3></div><div class="popContent"><div class="popContentbg"></div></div><div class="popButton" ></div></div></div>'}});b.widget("hk.popTips",b.hk.popWin,{options:{popClass:"popTips",tipsType:"top",tipsTarget:null,offset:5,show:!1,modal:!1,isBindLeave:!0,isUpdataMsg:!0,isarrow:!0,draggable:!1,arrow:"left",width:"auto",autoOpen:!1,closeButton:!1,showTipsClose:!1,positionCollision:"none"},
_create:function(){var a=this.options,c=this;this.target=this.element;this.element=b("<span>");this.updataMsg();this.createHTML();a.isarrow&&b("<i><b></b></i>").addClass("tips").prependTo(this.wrap);a.isBindLeave&&this.target.bind("mouseenter",function(){c.open()}).bind("mouseleave",function(){c.close()});b.hk.popWin.prototype._create.apply(this)},updataMsg:function(){this.element.html(this.target.data("msg"))},updataTipsType:function(){var a=this.options,c=this.target.data("position")||a.tipsType;
this.wrap.removeClass("popTips-"+a.tipsType).addClass("popTips-"+c);return a.tipsType=c},open:function(){this.options.isUpdataMsg&&this.updataMsg();b.hk.popWin.prototype.open.call(this)},_position:function(){var a=this.options,c=a.position,e=this.updataTipsType(),d=a.offset;if(!b.isPlainObject(c)){switch(e){case "top":c="bottom";break;case "bottom":c="top";break;case "right":c="top";break;case "left":c="top";break;default:e="top",c="bottom"}a.position={of:this.target,my:(e=="left"?"right":"left")+
" "+c,at:(e=="right"?"right":"left")+" "+(e=="bottom"?"bottom":"top"),offset:(e=="top"||e=="bottom"?"0":e=="left"?-d:d)+" "+(e=="left"||e=="right"?"0":e=="top"?-d:d)}}b.hk.popWin.prototype._position.call(this,a.position)}})})(jQuery);
(function(b){b.widget("hk.popover",{options:{placement:"right",title:"",content:"",width:280,classTitle:"",classContent:""},_create:function(){var c=this;this.element.on("click",function(){c.tip?(c.tip.remove(),c.tip=null):(c.createHTML(),c.position(),c.tip.delegate(".popover1-close","click",function(){c.tip.remove();c.tip=null;return!1}))})},position:function(){var c,d,a,f,e,h,g,i;d=this.tip;d.css({top:0,left:0,display:"block"});f=this.getElementPos(this.element);a=f.top;f=f.left;e=this.element.outerWidth();
h=this.element.outerHeight();g=d.outerWidth();i=d.outerHeight();switch(this.options.placement){case "bottom":c={top:a+h,left:f+e/2-g/2};break;case "top":c={top:a-i,left:f+e/2-g/2};break;case "left":c={top:a+h/2-i/2,left:f-g};break;case "right":c={top:a+h/2-i/2,left:f+e}}if(c.top<=0)c.top=1;if(c.left<=0)c.left=1;if(c.left>=b(document).width()-g)c.left=b(document).width()-g-1;d.offset(c)},createHTML:function(){var c=[],d;d=this.getTitle();c.push('<div class="popover1 '+this.options.placement+'" style="z-index:201"><div class="arrow"></div>');
c.push('<div class="popover1-inner" style="width:'+this.options.width+'px"><a href="#" class="popover1-close" role="button"><span>close</span></a>');c.push('<h3 class="popover1-title '+this.options.classTitle+'">'+d+'</h3><div class="popover1-content '+this.options.classContent+'">'+this.getContent()+"</div></div></div>");this.tip=b(c.join("")).appendTo("body");d||this.tip.find(".popover1-title").css("display","none")},getTitle:function(){var c=this.element;return this.options.title||c.attr("data-original-title")},
getContent:function(){var c=this.element;return this.options.content||c.attr("data-content")||""},getElementPos:function(c){var b={top:0,left:0},c=c.offset();b.top+=c.top;b.left+=c.left;return b}})})(jQuery);
(function(b,c){var d={popClass:"popPrompt",autoOpen:!0,closeDestroy:!0,reserve:!1,show:!1,width:360,height:"auto",closeButton:!1,type:["ok","error","stop","question","notice","attention","tips","alarm"]},a={defaultTitle:language.text("dialog.info"),defaultLevel:"attention",okbutton:language.text("dialog.ok"),okclass:"buttonM bBlue",cancelclass:"buttonM bDefault",cancelbutton:language.text("dialog.cancel"),defaultTempl:'<div class="popMsg"><i class="pop_icon"></i><div class="popMsgContent"></div></div>',
defaultPromptTempl:'<div class="popPromptMsg"><span></span><br/><input type="text" id="popup_prompt" class="auto-input"  /></div>',defaultPromptValue:language.text("dialog.input")},f={popClass:"popSticky",autoOpen:!0,closeDestroy:!0,reserve:!1,show:"slide",speed:"fast",width:360,modal:!1,height:"auto",minHeight:93,autoclose:2E3,closeButton:!0,type:["ok","error","stop","question","notice","attention","tips","alarm"],html:!1},e={defaultTempl:'<div class="popMsg"><i class="pop_icon"></i><div class="popMsgContent"><h5></h5><p></p></div></div>'},
h=function(b){b=c.isPlainObject(b)?b:{};!c.isFunction(b.callback)&&(b.callback=function(){});b.title==null&&(b.title=a.defaultTitle);b.level==null&&(b.level=a.defaultLevel);return b=c.extend(!0,{},d,b)},g=function(b){var e,d=b.html?b.html.find("#popup_prompt"):{};b.buttons=[{text:a.okbutton,"class":a.okclass,click:function(){this.close();d.length?b.callback.call(this,d.val()):b.callback.call(this,!0)}}];b.isCancelButton&&b.buttons.push({text:a.cancelbutton,"class":a.cancelclass,click:function(){this.close();
d.length?b.callback.call(this,!1):b.callback.call(this,null)}});b.html?e=b.html:(e=c(a.defaultTempl),e.find(".pop_icon").addClass(b.level),e.find(".popMsgContent").html(b.msg));e.popWin(b)},i=function(a,b,e,d,f){if(c.isPlainObject(a))return a;var g={};g.msg=a;if(c.isPlainObject(b))f=b;else if(c.isPlainObject(e))f=e,c.isFunction(b)?d=b:e=b,b=null;else if(c.isFunction(b))d=b,b=null;else if(c.isFunction(e))f=d,d=e,e=b,b=null;else if(e==null&&typeof b=="string")e=b,b=null;else if(c.isPlainObject(d))f=
d,d=f.callback;g.title=typeof b=="string"&&b||(f?f.title:null);g.level=typeof e=="string"&&e||(f?f.level:null);g.callback=f?f.callback||null:d;g.afterclose=f?f.afterclose||null:null;g.afteropen=f?f.afteropen||null:null;(g.options=f)&&f.type&&(g.type=f.type);return g},j={jAlert:function(a,c,b,e){e=h(i(a,c,b,e));a:{for(var d=openPopWinOptList.length,f=0;f<d;f++)if(a==openPopWinOptList[f].msg&&c==openPopWinOptList[f].title&&b==openPopWinOptList[f].level){a=!0;break a}a=!1}a||(g(e),openPopWinOptList&&
openPopWinOptList.push({msg:e.msg,title:e.title,level:e.level}))},jConfirm:function(a,c,b){a=h(i(a,c,"question",b));a.level="question";a.isCancelButton=!0;g(a)},jPrompt:function(b,e,d,f){b=h(i(b,d,"attention",f));b.isCancelButton=!0;b.html=c(a.defaultPromptTempl);b.value=e||b.value;b.html.find("span").html(b.msg);b.html.find("input").val(b.value||a.defaultPromptValue);g(b)},jSticky:function(a,b,d,g,h){var j=c(e.defaultTempl),k=i(a,b,d,g,h)||{},k=c.extend({},k,k.options),b=k.title,d=k.level?k.level:
k.type||"attention",a=j.find("i"),g=j.find("h5"),h=j.find("p");k.afterclose=k.afterclose||k.callback;if(k.html)j=c(k.message);else{delete k.title;if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,c){var b=this.length>>>0,e=Number(c)||0,e=e<0?Math.ceil(e):Math.floor(e);for(e<0&&(e+=b);e<b;e++)if(e in this&&this[e]===a)return e;return-1};d&&f.type.indexOf(d)>-1?(a.addClass(d),j.addClass("popSticky-icon")):a.hide();b?g.html(b):g.hide();h.html(k.msg||k.message)}j.popWin(c.extend(!0,{},f,
k,{open:function(a,c){var b=c.options;if(b.autoclose)c.leaveTM=setTimeout(function(){c.close()},b.autoclose);k.open&&k.open.call(this,a,c);try{b.afteropen&&b.afteropen.call(this,b)}catch(e){}}}))}};c.alerts=c.alerts||{};c.extend(b,j);c.extend(c.alerts,{alert:j.jAlert,confirm:j.jConfirm,prompt:j.jPrompt});c.sticky=j.jSticky})(window,jQuery);var openPopWinOptList=[];
(function(b,c){var d={ifrHTML:'<div class="dialog" name="{id}" parentSrc="{href}" style="padding:0;overflow:hidden;"><div class="loading-overlay"><div class="loading-m"><i></i><span>\u6b63\u5728\u52a0\u8f7d\u4e2d\uff0c\u8bf7\u7a0d\u540e...</span></div><div class="shadow"></div></div><iframe src="{src}" dialogIframe="true" id="{id}" name = "{id}" target="_self" frameborder="0" scrolling="auto" class="autoIframe dialog-frame"></iframe></div>',ajaxHTML:'<div class="dialog" id="{id}"></div>',treeResHTML:'<div class="dialog" id="{id}"><div class="dualBoxes clearfix"> <div class="leftBox"><h6>'+
language.text("dialog.alternateRes")+'</h6><div class=""><ul id="{treeId}" class="ztree"></ul></div></div><div class="dualControl">  <p><a id="btn-camera-sel" class="buttonS bDefault" href="javascript:void(0);">'+language.text("add")+' &gt;</a></p> <p><a id="btn-camera-unsel" class="buttonS bDefault" href="javascript:void(0);">&lt; '+language.text("delete")+'</a></p> </div><div class="rightBox"><h6>'+language.text("dialog.selectedRes")+'</h6><div class="datatable"> <table id="{listId}" cellspacing="0" cellpadding="0" width="100%" class="tLight checkAll"> <thead><tr><td> <span class="check"> <input id="checkAll" type="checkbox"></span></td> <td>'+
language.text("dialog.resourceName")+"</td> </tr></thead><tbody></tbody></table></div></div></div></div>",parseStr:function(a,c){return a.replace(/{([^}]*)}/g,function(a,b){return c[b]||""})},run:function(a){var b=a.close,e=a.el,a=c.extend(!0,{autoOpen:!0,modal:!0,resizable:!1,targetPage:window,width:500},a,{close:function(){b&&b.call(this,a);e.remove()}});return e.popWin(a)}};b.popWin=function(a){var a=a||{},b=c("base").attr("href")||"",e,h,g;if(e=a.iframeSrc)h=(/^\/|^https?\:\/\//i.test(e)?"":b)+
e,h=/\?/gi.test(h)?h+"&isDialog=true":h+"?isDialog=true&time="+new Date,a.iframeSrc=h,g=c(d.parseStr(d.ifrHTML,{id:a.id,href:e,src:""})).appendTo("body"),g.find("iframe").on("load",function(){g.find(".loading-overlay").hide()});else if(a.ajax&&a.ajax.url){h=a.ajax.url;h=(/^\/|^https?\:\/\//i.test(h)?"":b)+h;g=c(d.parseStr(d.ajaxHTML,{id:a.id}));var i=a.ajax.success;a.ajax.success=function(){var a=i&&i.apply(this,arguments);typeof a==="string"&&a.charAt(0)==="<"&&a.charAt(a.length-1)===">"&&a.length>=
3&&g.empty().append(a);return a};g.load(a.ajax.url,a.ajax.data||{},a.ajax.success);g.ajaxSuccess(function(a,b){if(b.status==200){var c=b.getResponseHeader("is-refresh"),e=b.getResponseHeader("in-login"),d=b.getResponseHeader("refresh-url");if(c=="1"||c==1||e=="1"||e==1)if(d==null||d=="")window.location.reload();else try{d=decodeURI(d),top.location.href=d}catch(f){window.location.reload()}}})}else if(a.el)g=a.el[0]?c(a.el[0].outerHTML):c([]),g.appendTo("body");else if(a.buildInType=="treeResHTML")g=
c(d.parseStr(d[a.buildInType],{id:a.id,treeId:a.treeId,listId:a.listId})).appendTo("body");else return;a.el=g;a=d.run(a);e&&g.find("iframe").attr("src",h);return a};b.dialog=function(a){a=c.extend(a,{dialogClass:"pop-dialog"});typeof b.popWin==="function"?b.popWin(c.extend(a,{originalPage:b,originalHref:location.href})):b.popWin(a)};c.fn.dialog=function(a){typeof a!=="string"&&(a=c.extend(a,{dialogClass:"pop-dialog"}));return this.popWin.apply(this,arguments)};c.extend({dialog:function(a){a=c.extend(a,
{dialogClass:"pop-dialog"});if(!a.id||!c("#"+a.id).length)return c.extend(a||{},{closeDestroy:!0}),a.displayCtx&&typeof a.displayCtx.popWin==="function"?a.displayCtx.popWin(c.extend(a,{originalPage:a.displayCtx,originalHref:a.displayCtx.location.href})):typeof top.popWin==="function"?top.popWin(c.extend(a,{originalPage:window,originalHref:location.href})):window.popWin(a)},buildInDialog:function(a){c.extend(a||{},{height:550,width:600});var b=c.dialog(a),e=c("#"+a.treeId).tree(a.treeSettings),d;c("#btn-camera-sel").on("click",
function(){e=c("#"+a.treeId).tree();d=e.getCheckedNodes(!0);if(d.length)for(var b=0,f=d.length;b<f;b++)d[b].extra&&d[b].extra.type=="res"&&(e.hideNode(d[b]),c("#"+a.listId).find("tbody").append('<tr><td><span class="check"><input data-id="'+d[b].id+'" type="checkbox"></span></td><td>'+d[b].label+"</td></tr>"));return!1});c("#btn-camera-sel").on("click",function(){e=c("#"+a.treeId).tree();d=e.getCheckedNodes(!0);if(d.length)for(var b=0,f=d.length;b<f;b++)d[b].extra&&d[b].extra.type=="res"&&(e.hideNode(d[b]),
c("#"+a.listId).find("tbody").append('<tr><td><span class="check"><input data-id="'+d[b].id+'" type="checkbox"></span></td><td>'+d[b].label+"</td></tr>"));return!1});c("#btn-camera-unsel").on("click",function(){c("#"+a.listId).find("tbody input:checked").each(function(){c(this).attr("data-id");e=c("#"+a.treeId).tree();c(this).closest("tr").remove();var b=e.getNodeById(c(this).attr("data-id"));e.showNode(b);e.checkNode(b,!1,!1)}).length||jAlert(language.text("dialog.deleteMessage"),language.text("dialog.info"),
"attention")});return b},sticky:function(a,b,c,d,g){jSticky(a,b,c,d,g)}})})(window,jQuery);
$(function(){(function(){function b(d){d==null||d===0?d=$("#navbar li.active a:first"):(d=$('#navbar a[menucode="'+d+'"]:first'),d.length||(d=b(0)));return d}$.hideNav=function(){$("#content>.breadLine").hide()};$.topNav=function(d,a,f){if(typeof eventsManage!="undefined")try{if(eventsManage.trigger("positions",d.html(),d.attr("menu-code"),a),/msie/.test(navigator.userAgent.toLowerCase()))for(var e=0,h=$("#content>.breadLine").find("span").length;e<h;e++){var g=$($("#content>.breadLine").find("span")[e]).css("max-width");
(g!==void 0||g!==null)&&$($("#content>.breadLine").find("span")[e]).width()>=parseInt(g)&&$($("#content>.breadLine").find("span")[e]).css("width",g)}}catch(i){}else setTimeout(function(){try{if(d!=null&&d.context!=null)$.topNav(d.attr("menu-code"),d,a);else{if(a==null||a=="")a='<UL class="breadcrumbs"></UL>';a.context==null&&(a=$(a));a.find("a").each(function(a,b){b.setAttribute("_href",b.getAttribute("href"));b.setAttribute("href","javascript:void(0);");b.setAttribute("frames",f.join(","))});var e=
b(d);if(e.length)for(var g=e.parent("li");g.length;){if(a.find("li").length)g.clone()[0].outerHTML?a.prepend(g.clone()[0].outerHTML):a.prepend(g.clone());else{var h=g.clone();h.html(h.find("a").html())[0].outerHTML?a.html(h.html(h.find("a").html())[0].outerHTML):a.html(h.html(h.find("a").html()))}a.find(".ddmenu").remove();g=g.parent("ul").closest("li")}var i=$("#top .topNav>li.active");i.length&&(i.clone()[0].outerHTML?a.prepend(i.clone()[0].outerHTML):a.prepend(i.clone()));var n=a.find("li:last");
n.length>0&&n.find("a").length>0&&n.html(n.find("a").html());pt&&pt.lang==="zh_cn"&&a.find("li span").each(function(a,b){var c=$(b).text();c.length>14&&$(b).text(c.substring(0,14)+"\u2026")});a[0].outerHTML?$("#content>.breadLine").html(a[0].outerHTML).show():$("#content>.breadLine").html(a).show();$("#navbar .mainNav").find(".nav > li").removeClass("active");e.parents(".ddmenu").length?e.parents(".ddmenu").parent().addClass("active"):e.parent().addClass("active")}}catch(p){}},0)};$("#content>.breadLine>ul.breadcrumbs>li>a").live("mousedown",
function(){var b=this.getAttribute("_href");if(!b)return!0;var a=window,c=this.getAttribute("forceFrame"),e=null;c?(a=a.frames[c])||(a=window.frames.mainFrame.frames[c]):e=this.getAttribute("frames");if(e&&(c=this.getAttribute("frames").split(","),c!=null))for(e=c.length;e>0;e--)a.frames[c[e-1]]&&(a=a.frames[c[e-1]]);(c=this.getAttribute("target"))&&(a.location.target=c);a.location.href=b;a.location.target=null;return!1})})();var b=function(b){b=b||window.event;if((b.wheelDelta||b.detail)&&b.ctrlKey)b.preventDefault(),
b.returnValue=!1};document.addEventListener&&document.addEventListener("DOMMouseScroll",b,!1);window.onmousewheel=document.onmousewheel=b;$(".breadcrumbs").xBreadcrumbs();(function(){function b(a){a.length&&($.browser.msie<8&&a.delegate(".nav > li","mouseenter",function(){$(this).addClass("hover")}).delegate(".nav > li","mouseleave",function(){$(this).removeClass("hover")}),a.delegate(".nav > li > a","click",function(){$(this).attr("autoactive")!="false"&&d(a,$(this))}),a.delegate(".ddmenu li a",
"click",function(){$(this).attr("autoactive")!="false"&&d(a,$(this).parents(".ddmenu"))}),$.fn.bgiframe&&$(".ddmenu",a).bgiframe())}function d(a,b){a.find(".nav > li").removeClass("active");b.parent().addClass("active")}var a=$("#navbar .mainNav"),f=$("#navbar .secNav");b(a);b(f)})();$("#subNav").length>0&&$("#subNav a").click(function(){var b=$(this).attr("href"),d=$(this).attr("target");$('iframe[name="'+d+'"]').attr("src",b);$("#subNav li").removeClass("active");$(this).parent().addClass("active");
return!1})});
var loader=function(b){return{show:function(c,d){var a=c||language.text("loading"),a=b('<div id="loaderTop" class="loading-overlay"><div class="loading-m"><i></i><span>'+a+'</span></div><div class="shadow"></div></div>');b("#loaderTop").length>0&&b("#loaderTop").remove();b("body").append(a);b.fn.bgiframe&&b("#loaderTop").bgiframe();b.isOcx&&b.isOcx.needModal()&&(b("#loaderTop").data("hasModal",!0),b.isOcx.createModal(document.getElementById("mainFrame").contentWindow));var f=b(".loading-m",a).outerWidth(),
f=parseInt(f)/2,e=b(".loading-m",a).outerHeight(),e=parseInt(e)/2;b(".loading-m",a).css({marginTop:"-"+e+"px",marginLeft:"-"+f+"px"});try{d&&d()}catch(h){}},update:function(c){b("#loaderTop .loading-m span").text(c)},hide:function(c){b.isOcx&&b("#loaderTop").data("hasModal")&&(b("#loaderTop").removeData("hasModal"),b.isOcx.removeModal(document.getElementById("mainFrame").contentWindow));b("#loaderTop").hide().remove();try{c&&c()}catch(d){}}}}(jQuery,loader||{}),progress=function(b){return{show:function(c,
d,a,f){d=d||language.text("loading");c=c||0;c=b('<div id="progressTop" class="progress-overlay"><div class="progress-m"><div class="progressbar"><div class="progress progress-small progress-info"><div class="filler"><div class="bar" style="width:'+c+'%"> </div></div></div><div class="percent"><b>'+c+'%</b></div><div class="elapsed">'+d+'</div><div class="actions clear" style="display:none;"><a id="btn_progress_hide" href="javascript:void(0);" class="buttonS bBlue">'+language.text("ui.progress.runBack")+
"</a></div></div></div>"+((a&&!0)==!0?" ":'<div class="shadow"></div>')+"</div>");b("#progressTop").length>0&&b("#progressTop").remove();b("body").append(c);b.fn.bgiframe&&b("#progressTop").bgiframe();f&&f()},update:function(c,d,a){b("#progressTop .bar").css("width",c+"%");b("#progressTop .percent b").text(c+"%");b("#progressTop .elapsed").text(d);typeof a=="function"&&setTimeout(function(){a()},1E3)},showButton:function(c){var d=this;b("#progressTop .actions").show("fade");b("#btn_progress_hide").on("click",
function(){b(this).attr("disabled")||d.hide(c)})},hide:function(c){b("#btn_progress_hide").attr("disabled","disabled");b("#progressTop").fadeOut("slow",function(){b(this).remove();c&&c()})}}}(jQuery,progress||{});
(function(b){function c(a,c,e,d){d={data:d||d===0||d===!1?d:c?c.data:{},_wrap:c?c._wrap:null,tmpl:null,parent:c||null,nodes:[],calls:i,nest:j,wrap:m,html:o,update:q};a&&b.extend(d,a,{nodes:[],parent:c});if(e)d.tmpl=e,d._ctnt=d._ctnt||d.tmpl(b,d),d.key=++u,(v.length?s:k)[u]=d;return d}function d(c,e,f){var h,f=f?b.map(f,function(a){return typeof a==="string"?c.key?a.replace(/(<\w+)(?=[\s>])(?![^>]*_tmplitem)([^>]*)/g,"$1 "+p+'="'+c.key+'" $2'):a:d(a,c,a._ctnt)}):c;if(e)return f;f=f.join("");f.replace(/^\s*([^<\s][^<]*)?(<[\w\W]+>)([^>]*[^>\s])?\s*$/,
function(c,d,e,f){h=b(e).get();g(h);d&&(h=a(d).concat(h));f&&(h=h.concat(a(f)))});return h?h:a(f)}function a(a){var c=document.createElement("div");c.innerHTML=a;return b.makeArray(c.childNodes)}function f(a){return new Function("jQuery","$item","var $=jQuery,call,__=[],$data=$item.data;with($data){__.push('"+b.trim(a).replace(/([\\'])/g,"\\$1").replace(/[\r\t\n]/g," ").replace(/\$\{([^\}]*)\}/g,"{{= $1}}").replace(/\{\{(\/?)(\w+|.)(?:\(((?:[^\}]|\}(?!\}))*?)?\))?(?:\s+(.*?)?)?(\(((?:[^\}]|\}(?!\}))*?)\))?\s*\}\}/g,
function(a,c,d,e,f,g,i){a=b.tmpl.tag[d];if(!a)throw"Unknown template tag: "+d;d=a._default||[];g&&!/\w$/.test(f)&&(f+=g,g="");f?(f=h(f),i=i?","+h(i)+")":g?")":"",i=g?f.indexOf(".")>-1?f+h(g):"("+f+").call($item"+i:f,g=g?i:"(typeof("+f+")==='function'?("+f+").call($item):("+f+"))"):g=i=d.$1||"null";e=h(e);return"');"+a[c?"close":"open"].split("$notnull_1").join(f?"typeof("+f+")!=='undefined' && ("+f+")!=null":"true").split("$1a").join(g).split("$1").join(i).split("$2").join(e||d.$2||"")+"__.push('"})+
"');}return __;")}function e(a,c){a._wrap=d(a,!0,b.isArray(c)?c:[w.test(c)?c:b(c).html()]).join("")}function h(a){return a?a.replace(/\\'/g,"'").replace(/\\\\/g,"\\"):null}function g(a){function d(a){function f(a){var y;a+=e;y=h[a]=h[a]||c(l,k[l.parent.key+e]||l.parent),l=y}var g,i=a,l,j;if(j=a.getAttribute(p)){for(;i.parentNode&&(i=i.parentNode).nodeType===1&&!(g=i.getAttribute(p)););if(g!==j){i=i.parentNode?i.nodeType===11?0:i.getAttribute(p)||0:0;if(!(l=k[j]))l=s[j],l=c(l,k[i]||s[i]),l.key=++u,
k[u]=l;r&&f(j)}a.removeAttribute(p)}else if(r&&(l=b.data(a,"tmplItem")))f(l.key),k[l.key]=l,i=(i=b.data(a.parentNode,"tmplItem"))?i.key:0;if(l){for(g=l;g&&g.key!=i;)g.nodes.push(a),g=g.parent;delete l._ctnt;delete l._wrap;b.data(a,"tmplItem",l)}}var e="_"+r,f,g,h={},i,j,m;i=0;for(j=a.length;i<j;i++)if((f=a[i]).nodeType===1){g=f.getElementsByTagName("*");for(m=g.length-1;m>=0;m--)d(g[m]);d(f)}}function i(a,b,c,d){if(!a)return v.pop();v.push({_:a,tmpl:b,item:this,data:c,options:d})}function j(a,c,d){return b.tmpl(b.template(a),
c,d,this)}function m(a,c){var d=a.options||{};d.wrapped=c;return b.tmpl(b.template(a.tmpl),a.data,d,a.item)}function o(a,c){var d=this._wrap;return b.map(b(b.isArray(d)?d.join(""):d).filter(a||"*"),function(a){if(c)a=a.innerText||a.textContent;else{var b;if(!(b=a.outerHTML))b=document.createElement("div"),b.appendChild(a.cloneNode(!0)),b=b.innerHTML;a=b}return a})}function q(){var a=this.nodes;b.tmpl(null,null,null,this).insertBefore(a[0]);b(a).remove()}var n=b.fn.domManip,p="_tmplitem",w=/^[^<]*(<[\w\W]+>)[^>]*$|\{\{\! /,
k={},s={},t,x={key:0,data:{}},u=0,r=0,v=[];b.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,c){b.fn[a]=function(d){var e=[],d=b(d),f,g,h;f=this.length===1&&this[0].parentNode;t=k||{};if(f&&f.nodeType===11&&f.childNodes.length===1&&d.length===1)d[c](this[0]),e=this;else{g=0;for(h=d.length;g<h;g++)r=g,f=(g>0?this.clone(!0):this).get(),b(d[g])[c](f),e=e.concat(f);r=0;e=this.pushStack(e,a,d.selector)}d=t;t=null;b.tmpl.complete(d);
return e}});b.fn.extend({tmpl:function(a,c,d){return b.tmpl(this[0],a,c,d)},tmplItem:function(){return b.tmplItem(this[0])},template:function(a){return b.template(a,this[0])},domManip:function(a,c,d){if(a[0]&&b.isArray(a[0])){for(var e=b.makeArray(arguments),f=a[0],g=f.length,h=0,i;h<g&&!(i=b.data(f[h++],"tmplItem")););i&&r&&(e[2]=function(a){b.tmpl.afterManip(this,a,d)});n.apply(this,e)}else n.apply(this,arguments);r=0;t||b.tmpl.complete(k);return this}});b.extend({tmpl:function(a,f,g,h){var i=!h;
if(i)h=x,a=b.template[a]||b.template(null,a),s={};else if(!a)return a=h.tmpl,k[h.key]=h,h.nodes=[],h.wrapped&&e(h,h.wrapped),b(d(h,null,h.tmpl(b,h)));if(!a)return[];typeof f==="function"&&(f=f.call(h||{}));g&&g.wrapped&&e(g,g.wrapped);f=b.isArray(f)?b.map(f,function(b){return b?c(g,h,a,b):null}):[c(g,h,a,f)];return i?b(d(h,null,f)):f},tmplItem:function(a){var c;for(a instanceof b&&(a=a[0]);a&&a.nodeType===1&&!(c=b.data(a,"tmplItem"))&&(a=a.parentNode););return c||x},template:function(a,c){if(c)return typeof c===
"string"?c=f(c):c instanceof b&&(c=c[0]||{}),c.nodeType&&(c=b.data(c,"tmpl")||b.data(c,"tmpl",f(c.innerHTML))),typeof a==="string"?b.template[a]=c:c;return a?typeof a!=="string"?b.template(null,a):b.template[a]||b.template(null,w.test(a)?a:b(a)):null},encode:function(a){return(""+a).split("<").join("&lt;").split(">").join("&gt;").split('"').join("&#34;").split("'").join("&#39;")}});b.extend(b.tmpl,{tag:{tmpl:{_default:{$2:"null"},open:"if($notnull_1){__=__.concat($item.nest($1,$2));}"},wrap:{_default:{$2:"null"},
open:"$item.calls(__,$1,$2);__=[];",close:"call=$item.calls();__=call._.concat($item.wrap(call,__));"},each:{_default:{$2:"$index, $value"},open:"if($notnull_1){$.each($1a,function($2){with(this){",close:"}});}"},"if":{open:"if(($notnull_1) && $1a){",close:"}"},"else":{_default:{$1:"true"},open:"}else if(($notnull_1) && $1a){"},html:{open:"if($notnull_1){__.push($1a);}"},"=":{_default:{$1:"$data"},open:"if($notnull_1){__.push($.encode($1a));}"},"!":{open:""}},complete:function(){k={}},afterManip:function(a,
c,d){var e=c.nodeType===11?b.makeArray(c.childNodes):c.nodeType===1?[c]:[];d.call(a,c);g(e);r++}})})(jQuery);
var _model=function(){function b(){}function c(b,c){for(var f in c)a.call(c,f)&&(b[f]=typeof c[f]==="function"&&typeof b[f]=="function"&&d.test(c[f])?function(a,b,c){return function(){var a=this._super,d;this._super=c;d=b.apply(this,arguments);this._super=a;return d}}(f,c[f],b[f]):c[f])}var d=/xyz/.test(function(){})?/_super/:/.*/,a=Object.prototype.hasOwnProperty,f;b.prototype={batch:function(b){for(var c in this)a.call(this,c)&&b.test(c)&&this[c].call(this)},setOptions:function(a){typeof a=="object"&&
this.options&&$.extend(!0,this.options,a);return this},getmodel:function(c){if(a.call(this,c))return this[c]},addmodel:function(a,c){for(var a=a.split("."),d=this,f,j=0;f=a[j];j++)if(d=d.getmodel(f),!d){if(c===!1)return;d=this[f]=new b}return d}};f=new b;return{define:function(){for(var a=Array.prototype.slice.call(arguments),b=a.pop(),d=a.shift(),a=typeof a[0]==="string"?a:a[0]||[],i=f.addmodel(d),d=[i],j=0,m=a.length,o;j<m;j++)o=a[j],d.push(f.addmodel(o,!1));typeof b==="function"?(b=b.apply(null,
d))&&c(i,b):c(i,b);if(!i.__initialize)eventsManage.make(i),i.__initialize=!0;if(i.domready&&!i.__domready)$(function(){i.domready()}),i.__domready=!0;i.init&&i.init();return i},require:function(a){return f.addmodel(a,!1)}}}(),eventsManage=function(){return{_events:$({}),bind:function(b,c,d){c=d?$.proxy(c,d):c;this._events.bind(b,c)},trigger:function(b){var c=Array.prototype.slice.call(arguments,1);return this._events.trigger(b,c)},unbind:function(b,c){this._events.unbind(b,c)},make:function(b){for(var c in this)this.hasOwnProperty(c)&&
(b[c]=this[c]);b._events=$({})}}}();
_model.define("menu",function(){var b={tmplurl:"",cssactive:"active",csshover:"hover",ajaxResponseReader:{data:"data"},tmplcontent:"[data-menu],[data-menu-sub],[data-menu-common]",tmpl:"[tmpl-menu],[tmpl-menu-sub],[tmpl-menu-common]","tmpl-menu":'<script type="text/x-jquery-tmpl" tmpl-menu>{{each(i, d) data}}<li><a href="javascript:void(0);" data-position = "top" url="{{= d.href}}" menuType="{{= d.type}}" openType="{{= d.openType}}" menuId="{{= d.menuId}}" customAppUrl="{{= d.customAppUrl}}" >{{= d.name}}</a></li>{{/each}}<li id="navThirdMoreLink" class="displayNone"><a href="javascript:void(0);" class="more"><span>'+language.text("menu.more")+
'</span></a><ul style="display:none"><iframe style="width:100%; height:100%; position: absolute; z-index: -1; left: 0px; top: 0px;opacity:0;filter: Alpha(opacity = 0);"></iframe>  </ul></li><\/script>',"tmpl-menu-sub":'<script type="text/x-jquery-tmpl" tmpl-menu-sub><div class="block block-home">{{each(i, d) data}}{{if d.data != null && d.data.length !=0}}<div class="nav_content"><h2><a href="javascript:void(0);"><span>{{= d.name}}</span></a></h2><ul>{{each(i,dd) data}}<li> {{if dd.className == "dash-empty"}}<a href="javascript:void(0);" data-position="sub" url="{{=dd.href}}" menuType="{{= dd.type}}" openType="{{= d.openType}}" menuId="{{= dd.menuId}}" code="{{= dd.code}}" serviceType="{{= dd.serviceType}}" customHomeMenuUrl="{{= dd.customHomeMenuUrl}}" class="icon_log {{= dd.className}}">{{if dd.imgurl != "" && dd.imgurl != null}}<img src="{{= dd.imgurl}}" style="width:72px;height:72px;"/>{{else}}<img src="../assets/default/images/dash-empty.png" style="width:72px;height:72px;"/>{{/if}}</a>{{else}}<a href="javascript:void(0);" data-position="sub" url="{{=dd.href}}" menuType="{{= dd.type}}" openType="{{= d.openType}}" menuId="{{= dd.menuId}}" code="{{= dd.code}}" serviceType="{{= dd.serviceType}}" customHomeMenuUrl="{{= dd.customHomeMenuUrl}}" class="icon_log {{= dd.className}}"></a>{{/if}}<span>{{= dd.name}}</span></li>{{/each}}</ul></div>{{/if}}{{/each}}</div><\/script>',
"tmpl-menu-common":'<script type="text/x-jquery-tmpl" tmpl-menu-common><li class="mainNav_map"><a href="javascript:void(0);" class="map_a"><i></i></a><div class="ddmenu"><iframe style="width:100%; height:100%; position: absolute; z-index: -1; left: -1px; top: 0px;opacity:0;filter: Alpha(opacity = 0);"></iframe><ul>{{each(i, d) data}}<li><a href="javascript:void(0);"  data-position="commonLeft" menucode="{{= d.menuId}}" menuid="{{= d.menuId}}" menuType="{{= d.type}}"  customAppUrl="{{= d.customAppUrl}}" openType="{{= d.openType}}" url="{{= d.href}}"><i></i><span>{{= d.name}}</span></a>{{if d.data != null && d.data.length != 0 }}<ul>{{each(i, d) data}}<li><a href="javascript:void(0);"  data-position="commonLeft" menucode="{{= d.menuId}}" menuid="{{= d.menuId}}" menuType="{{= d.type}}" customHomeMenuUrl="{{= d.customHomeMenuUrl}}" openType="{{= d.openType}}" url="{{= d.href}}"><i></i><span>{{= d.name}}</span></a></li>{{/each}}</ul>{{/if}} </li>{{/each}} </ul></div></li>{{each(i, d) data}}{{if data != null && data.length != 0 && active == 1}}{{each(i, d) data}}<li><a href="javascript:void(0);"  data-position="common" menucode="{{= d.menuId}}" menuid="{{= d.menuId}}" menuType="{{= d.type}}"  openType="{{= d.openType}}" url="{{= d.href}}"><i></i><span>{{= d.name}}</span></a>{{if data != null && data.length != 0}}<div class="ddmenu"><iframe style="width:100%; height:100%; position: absolute; z-index: -1; left: -1px; top: 0px;opacity:0;filter: Alpha(opacity = 0);"></iframe><ul>{{each(i, d) data}}<li><a href="javascript:void(0);" data-position="common"  menucode="{{= d.menuId}}" menuid="{{= d.menuId}}" menuType="{{= d.type}}"  openType="{{= d.openType}}" url="{{= d.href}}"><i></i><span>{{= d.name}}</span></a><ul>{{each(i, d) data}}<li><a href="javascript:void(0);"  menucode="{{= d.menuId}}" menuid="{{= d.menuId}}" menuType="{{= d.type}}"  openType="{{= d.openType}}" url="{{= d.href}}"><i></i><span>{{= d.name}}</span></a></li>{{/each}}</ul></li>{{/each}}</ul></div>{{/if}}</li>{{/each}}{{/if}}{{/each}}<li id="navThirdMoreLink1" style=""><a href="javascript:void(0);" class=""><span class="more"></span></a><div class="ddmenuMore"><iframe style="width:100%; height:100%; position: absolute; z-index: -1; left: 0px; top: 0px;opacity:0;filter: Alpha(opacity = 0);"></iframe><ul id="ddmenuUl"></ul></li><\/script>',
parentTag:"li",params:["menuId","href","target","active","parentId","name"],onMenuClick:null,onMenuMouseenter:null,onMenuMouseleave:null,data:null,hasBreadcrumbs:"#breadcrumbs"};return{options:b,inilize:!1,activedata:[],cachedata:{},menudata:{},domInit:function(){var c=this;this.elem=$(b.tmplcontent);this.template=$(b.tmpl);this.getdata();$(window).resize(function(){c.resizeWidth($("[data-menu-common]"))});c.resizeWidth($("[data-menu-common]"));b.data=null},getdata:function(){var c=this;c.elem.length<=
0||(b.data?this.generateMenu(b.data):b.tmplurl&&$.ajax({type:"post",dataType:"json",url:b.tmplurl,success:function(b){c.generateMenu.call(c,b)}}))},generateMenu:function(b){var d=this.options.tmplcontent.split(","),a=this.options.tmpl.split(","),f,e;this.menudata=b;this.parseData(b);for(var h=0,g=d.length;h<g;h++)if((f=$(d[h])).length)e=$(a[h]).length?$(a[h]):$(this.options[a[h].replace(/[\[\]]/g,"")]),f.html(e.tmpl(b));this.resetActive(this.activeId);this.batch(/^onEvent/);this.inilize=!0;this.trigger("inilize")},
getactive:function(){return this.activedata},isInit:function(){return this.inilize},getMenuById:function(b,d){for(var a in d)if(d.hasOwnProperty(a)&&d[a].menuId==b)return d[a]},getFirstChild:function(b,d){var a=function i(a){return a.selfSite?a.menuId:a.data&&a.data.length?i(a.data[0]):a.menuId};if(d.menuId==b)return a(d);else{var a=d.data,f;if(a)for(var e=0,h=a.length;e<h;e++)if(f=this.getFirstChild(b,a[e]))break;return f}},eraseData:function(b,d){var a={},f;for(f in d)d.hasOwnProperty(f)&&f!=b&&
(a[f]=d[f]);return a},parseData:function(b){for(var d=this.cachedata,a=this.options.ajaxResponseReader.data,f=b[a],e=0,h=f.length,g,i;e<h;e++){g=f[e];i=this.eraseData(a,g);if(typeof i.parentId!=null&&b.menuId!=null)i.parentId=b.menuId;if(i.active==1)this.activeId=i.menuId;d[i.menuId]=i;g.data&&g.data.length&&this.parseData(g)}},resetActive:function(b){var d=this.cachedata;if(b=d[b]){if(b.target&&b.target=="_blank"){(d=this.options.csshover)&&this.elem.find("."+d).removeClass(d);return}for(this.activedata=
[b];b=b.parentId;)b=d[b],this.activedata.unshift(b)}this.changeActiveClass();return this.getactive()},resizeWidth:function(b){var d=b.width()-$("#navThirdMoreLink1").width(),a=0,f=b.children(),e=f.length,h="";$.each(f,function(g){if(g!==e-1){a+=f.eq(g).width();f.eq(g).find(".ddmenu").removeAttr("style");if(a>d){for($("#navThirdMoreLink1").css("display","block");g<e-1;g++)f.eq(g).find("ul li").length!==0&&(f.eq(g).find(".ddmenu").removeAttr("style"),f.eq(g).children("a").children("i").addClass("menuMoreIcon")),
h+=f.eq(g)[0].outerHTML,f.eq(g).remove();$("#navThirdMoreLink1 ul#ddmenuUl").prepend(h);return!1}if(g==f.length-2&&a<d)if($("#navThirdMoreLink1  ul#ddmenuUl li").length!==0)for(var i=0;i<$("#navThirdMoreLink1  ul#ddmenuUl li").length;i++){if(f.eq(g+i).children("a").children("i").removeClass("menuMoreIcon"),$($("#navThirdMoreLink1  ul#ddmenuUl li")[0]).insertAfter(f.eq(g+i)),f=b.children(),a+=f.eq(g+i+1).width(),a>d)return $("#navThirdMoreLink1 ul#ddmenuUl").prepend(f.eq(g+i+1)),!1}else $("#navThirdMoreLink1").css("display",
"none")}})},changeActiveClass:function(){var b=this,d=this.options.cssactive,a=this.activedata,f=this.options.parentTag;d&&this.elem.find("."+d).removeClass(d);$.each(a,function(a,h){$("[menuId="+h.menuId+"]",b.elem).closest(f).addClass(d)})},onEventMenuClick:function(){var b=this;this.elem.on("click","a",function(d){var a=$(this).attr("menuId");b.resetActive(a);return b.clickval=b.menuClick.call(this,d,b,b.cachedata[a],a)})}}});
_model.define("menu",function(){return{menuClick:function(b,c,d,a){if(d){$.cookie&&$.cookie("hik-menuId",a);if(typeof c.options.onMenuClick=="function"){var f=c.getMenuById(a,c.cachedata);if(c.options.onMenuClick.call($(this),f)==!1)return eventsManage&&eventsManage.trigger("positions","",a,d.target?[d.target]:[window]),!1}f=$(this).attr("target")||d.target;d=$(this).attr("url")||d.href;c.options.hasBreadcrumbs&&eventsManage&&f!="_blank"&&eventsManage.trigger("positions","",a,f?[f]:[window]);if(b&&
b.originalEvent&&b.originalEvent.returnValue===!1)return!1;d=d.indexOf("?")>-1?d+"&random="+Math.floor(Math.random()*1E5):d+"?random="+Math.floor(Math.random()*1E5);f=="_blank"?window.open(d):f=="_top"?top.location.href=d:f=="_self"?window.location.href=d:f=="_parent"?window.parent.location.href=d:(f||(f="mainFrame"),b=$("#"+f),c=b.parent(),a=typeof b[0].contentWindow.$!=="function"?null:b[0].contentWindow.$("iframe"),a!==null?(a.each(function(){var a=$(this);if(a.length>0)a[0].src="about:blank",
a[0].contentWindow.document.write(""),a[0].contentWindow.close(),a.remove(),typeof CollectGarbage=="function"&&CollectGarbage()}),b[0].src="about:blank;",b[0].contentWindow.document.write(""),b[0].contentWindow.close(),b.remove(),typeof CollectGarbage=="function"&&CollectGarbage(),c.append('<iframe id="'+f+'" name="'+f+'" src="'+d+'" frameborder="0" class="autoIframe" scrolling="auto"></iframe>')):b.attr("src",d));return!1}},menuEnter:function(b,c){var d=$(this),a=c.options.csshover,f=d.parents("[data-menu-common]"),
e=f.width();a=="hover"?d.addClass(a):d.addClass("hover "+a);if((a=d.children("div")).length){$.isOcx&&$.isOcx.needModal()&&(d.data("hasModal",!0),$.isOcx.createModal(document.getElementById("mainFrame").contentWindow));a.show();var h=a.css("width"),g=a.css("height");a.children("iframe").css({width:h,height:g});f.width()-this.offsetLeft<a.width()&&d.parents(".ddmenuMore").length==0&&d[0].id!=="navThirdMoreLink1"&&d.children(".ddmenu").css({right:e-this.offsetLeft-d.width(),"-moz-box-shadow":" -3px 3px 4px #ababab",
"-webkit-box-shadow":"-3px 3px 4px #ababab","box-shadow":"-3px 3px 4px #ababab"})}},menuLeave:function(b,c){var d=$(this),a=c.options.csshover;a=="hover"?d.removeClass(a):d.removeClass("hover "+a);if((a=d.children("div")).length)$.isOcx&&d.data("hasModal")&&(d.removeData("hasModal"),$.isOcx.removeModal(document.getElementById("mainFrame").contentWindow)),a.hide()},onEventMenuHover:function(){var b=this;this.elem.on("mouseenter","li",function(c){return b.menuEnter.call(this,c,b)}).on("mouseleave",
"li",function(c){return b.menuLeave.call(this,c,b)})}}});
_model.define("position",["menu"],function(b,c){var d={templatecontent:"<ul>",isBindMenuClick:!0,template:'<li><a href="{href}"><span>{name}</span></a></li>',nonHrefTempl:"<li><span>{name}</span></li>"},a=/\{([^}]*)\}/g;return{options:d,init:function(){var a=this;c.options.hasBreadcrumbs&&(c.bind("inilize.positions",function(){a.viewpos()}),eventsManage.bind("positions",this.viewpos,this))},viewpos:function(b,e,h,g){if(c.options.hasBreadcrumbs){var i=this,j=$($.trim(e));if(!c.isInit())return c.bind("inilize.positions",
function(){i.viewpos(b,e);c.unbind("inilize.positions")}),!1;h&&(h=c.getFirstChild(h,c.menudata),c.resetActive(h));var h=c.getactive(),m=$(c.options.hasBreadcrumbs).empty(),o,q,n,p;n=0;for(p=h.length;n<p;n++)q=h[n],n==p-1&&!j.length?o=$(d.nonHrefTempl.replace(a,function(a,b){if(q[b])return q[b]})):(o=$(d.template.replace(a,function(a,b){if(q[b])return q[b]})),d.isBindMenuClick&&o.bind("click",function(a,d){return function(){c.menuClick.apply(d,[b,c,c.cachedata[a],a]);return!1}}(q.menuId,o.find("a")))),
m.append(o);j.find("a").each(function(a,b){var c=b.getAttribute("href"),d=window;/javascript:/g.test(c)&&b.setAttribute("href",c.replace(/.*?\(\'(.*)\'\)\;/,"$1"));$(b).bind("click",function(){return function(){for(var a=g.length;a>0;a--)d.frames[g[a-1]]&&(d=d.frames[g[a-1]]);(a=this.getAttribute("target"))&&(d.location.target=a);d.location.href=$(this).attr("href");d.location.target=null;return!1}}())});m.append(j)}}}});
