typeof JSON!=="object"&&(JSON={});
(function(){function b(a){return a<10?"0"+a:a}function a(){return this.valueOf()}function c(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var f=l[a];return typeof f==="string"?f:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function e(a,f){var b,m,k,l,n=g,j,d=f[a];d&&typeof d==="object"&&typeof d.toJSON==="function"&&(d=d.toJSON(a));typeof i==="function"&&(d=i.call(f,a,d));switch(typeof d){case "string":return c(d);case "number":return isFinite(d)?String(d):
"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";g+=o;j=[];if(Object.prototype.toString.apply(d)==="[object Array]"){l=d.length;for(b=0;b<l;b+=1)j[b]=e(b,d)||"null";k=j.length===0?"[]":g?"[\n"+g+j.join(",\n"+g)+"\n"+n+"]":"["+j.join(",")+"]";g=n;return k}if(i&&typeof i==="object"){l=i.length;for(b=0;b<l;b+=1)typeof i[b]==="string"&&(m=i[b],(k=e(m,d))&&j.push(c(m)+(g?": ":":")+k))}else for(m in d)Object.prototype.hasOwnProperty.call(d,m)&&(k=e(m,d))&&j.push(c(m)+
(g?": ":":")+k);k=j.length===0?"{}":g?"{\n"+g+j.join(",\n"+g)+"\n"+n+"}":"{"+j.join(",")+"}";g=n;return k}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},Boolean.prototype.toJSON=a,Number.prototype.toJSON=a,String.prototype.toJSON=a;var h,f,g,o,l,i;if(typeof JSON.stringify!==
"function")f=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=function(a,f,b){var c;o=g="";if(typeof b==="number")for(c=0;c<b;c+=1)o+=" ";else typeof b==="string"&&(o=b);if((i=f)&&typeof f!=="function"&&(typeof f!=="object"||typeof f.length!=="number"))throw Error("JSON.stringify");return e("",{"":a})};if(typeof JSON.parse!==
"function")h=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,JSON.parse=function(a,f){function b(a,g){var c,e,d=a[g];if(d&&typeof d==="object")for(c in d)Object.prototype.hasOwnProperty.call(d,c)&&(e=b(d,c),e!==void 0?d[c]=e:delete d[c]);return f.call(a,g,d)}var g,a=String(a);h.lastIndex=0;h.test(a)&&(a=a.replace(h,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+a+")"),typeof f==="function"?b({"":g},""):g;throw new SyntaxError("JSON.parse");}})();
function UserDataStorage(b){var a=document.createElement("div");a.style.display="none";a.style.behavior="url('#default#userData')";document.body.appendChild(a);if(b)b=(new Date).getTime()+b*1E3,a.expires=(new Date(b)).toUTCString();a.load("UserDataStorage");this.getItem=function(b){return a.getAttribute(b)||null};this.setItem=function(b,e){a.setAttribute(b,e);a.save("UserDataStorage")};this.removeItem=function(b){a.removeAttribute(b);a.save("UserDataStorage")}}
function CookieStorage(b,a){var c=function(){var a={},b=document.cookie;if(b==="")return a;for(var b=b.split("; "),e=0;e<b.length;e++){var c=b[e],i=c.indexOf("="),h=c.substring(0,i),c=c.substring(i+1),c=decodeURIComponent(c);a[h]=c}return a}(),e=[],h;for(h in c)e.push(h);this.length=e.length;this.key=function(a){if(a<0||a>=e.length)return null;return e[a]};this.getItem=function(a){return c[a]||null};this.setItem=function(f,g){f in c||(e.push(f),this.length++);c[f]=g;var h=f+"="+encodeURIComponent(g);
b&&(h+="; max-age="+b);a&&(h+="; path="+a);document.cookie=h};this.removeItem=function(a){if(a in c){delete c[a];for(var b=0;b<e.length;b++)if(e[b]===a){e.splice(b,1);break}this.length--;document.cookie=a+"=; max-age=0"}};this.clear=function(){for(var a=0;a<e.length;a++)document.cookie=e[a]+"=; max-age=0";c={};e=[];this.length=0}}
function hikStorage(b,a){if(b=="cookie")return new CookieStorage(a&&a.maxage,a&&a.path,a);else if(b=="session")if(typeof sessionStorage=="object")return sessionStorage;else throw Error("Local storage not avaliable.");else if(b=="local")if(typeof localStorage=="object")return localStorage;else if(typeof globalStorage=="object")return globalStorage[a&&a.domain||location.host];else throw Error("Local storage not avaliable.");else if(b=="global")if(typeof globalStorage=="object")return globalStorage[a&&
a.domain||location.host];else throw Error("Local storage not avaliable.");else if(b!="indexDB")return window.sessionStorage||window.UserDataStorage&&new UserDataStorage||new CookieStorage(a&&a.maxage,a&&a.path,a)};
