(function(p){var s={},t={},q={},l={treeId:"",treeObj:null,view:{addDiyDom:null,autoCancelSelected:!0,dblClickExpand:!0,expandSpeed:"fast",fontCss:{},nameIsHTML:!1,selectedMulti:!0,showIcon:!0,showLine:!0,showTitle:!0,txtSelectedEnable:!1},data:{key:{children:"children",name:"name",title:"",url:"url"},simpleData:{enable:!1,idKey:"id",pIdKey:"pId",rootPId:null},keep:{parent:!1,leaf:!1}},async:{enable:!1,contentType:"application/x-www-form-urlencoded",type:"post",dataType:"text",url:"",autoParam:[],
otherParam:[],dataFilter:null},callback:{beforeAsync:null,beforeClick:null,beforeDblClick:null,beforeRightClick:null,beforeMouseDown:null,beforeMouseUp:null,beforeExpand:null,beforeCollapse:null,beforeRemove:null,onAsyncError:null,onAsyncSuccess:null,onNodeCreated:null,onClick:null,onDblClick:null,onRightClick:null,onMouseDown:null,onMouseUp:null,onExpand:null,onCollapse:null,onRemove:null}},h={bind:[function(a){var b=a.treeObj,c=d.event;b.bind(c.NODECREATED,function(b,c,d){k.apply(a.callback.onNodeCreated,
[b,c,d])});b.bind(c.CLICK,function(b,c,d,f,g){k.apply(a.callback.onClick,[c,d,f,g])});b.bind(c.EXPAND,function(b,c,d){k.apply(a.callback.onExpand,[b,c,d])});b.bind(c.COLLAPSE,function(b,c,d){k.apply(a.callback.onCollapse,[b,c,d])});b.bind(c.ASYNC_SUCCESS,function(b,c,d,f){k.apply(a.callback.onAsyncSuccess,[b,c,d,f])});b.bind(c.ASYNC_ERROR,function(b,c,d,f,g,i){k.apply(a.callback.onAsyncError,[b,c,d,f,g,i])});b.bind(c.REMOVE,function(b,c,d){k.apply(a.callback.onRemove,[b,c,d])})}],unbind:[function(a){var b=
d.event;a.treeObj.unbind(b.NODECREATED).unbind(b.CLICK).unbind(b.EXPAND).unbind(b.COLLAPSE).unbind(b.ASYNC_SUCCESS).unbind(b.ASYNC_ERROR).unbind(b.REMOVE)}],caches:[function(a){var b=f.getCache(a);b||(b={},f.setCache(a,b));b.nodes=[];b.doms=[]}],nodes:[function(a,b,c,e,d,m){if(c){var g=f.getRoot(a),i=a.data.key.children;c.level=b;c.tId=a.treeId+"_"+ ++g.zId;c.parentTId=e?e.tId:null;c.open=typeof c.open=="string"?k.eqs(c.open,"true"):!!c.open;c[i]&&c[i].length>0?(c.isParent=!0,c.zAsync=!0):(c.isParent=
typeof c.isParent=="string"?k.eqs(c.isParent,"true"):!!c.isParent,c.open=c.isParent&&!a.async.enable?c.open:!1,c.zAsync=!c.isParent);c.isFirstNode=d;c.isLastNode=m;c.getParentNode=function(){return f.getNodeCache(a,c.parentTId)};c.getPreNode=function(){return f.getPreNode(a,c)};c.getNextNode=function(){return f.getNextNode(a,c)};c.isAjaxing=!1;f.fixPIdKeyValue(a,c)}}],proxys:[function(a){var b=a.target,c=f.getSetting(a.data.treeId),e="",o=null,m="",g="",i=null,h=null,j=null;if(k.eqs(a.type,"mousedown"))g=
"mousedown";else if(k.eqs(a.type,"mouseup"))g="mouseup";else if(k.eqs(a.type,"contextmenu"))g="contextmenu";else if(k.eqs(a.type,"click"))if(k.eqs(b.tagName,"span")&&b.getAttribute("treeNode"+d.id.SWITCH)!==null)e=k.getNodeMainDom(b).id,m="switchNode";else{if(j=k.getMDom(c,b,[{tagName:"a",attrName:"treeNode"+d.id.A}]))e=k.getNodeMainDom(j).id,m="clickNode"}else if(k.eqs(a.type,"dblclick")&&(g="dblclick",j=k.getMDom(c,b,[{tagName:"a",attrName:"treeNode"+d.id.A}])))e=k.getNodeMainDom(j).id,m="switchNode";
if(g.length>0&&e.length==0&&(j=k.getMDom(c,b,[{tagName:"a",attrName:"treeNode"+d.id.A}])))e=k.getNodeMainDom(j).id;if(e.length>0)switch(o=f.getNodeCache(c,e),m){case "switchNode":o.isParent?k.eqs(a.type,"click")||k.eqs(a.type,"dblclick")&&k.apply(c.view.dblClickExpand,[c.treeId,o],c.view.dblClickExpand)?i=n.onSwitchNode:m="":m="";break;case "clickNode":i=n.onClickNode}switch(g){case "mousedown":h=n.onZTreeMousedown;break;case "mouseup":h=n.onZTreeMouseup;break;case "dblclick":h=n.onZTreeDblclick;
break;case "contextmenu":h=n.onZTreeContextmenu}return{stop:!1,node:o,nodeEventType:m,nodeEventCallback:i,treeEventType:g,treeEventCallback:h}}],roots:[function(a){var b=f.getRoot(a);b||(b={},f.setRoot(a,b));b[a.data.key.children]=[];b.expandTriggerFlag=!1;b.curSelectedList=[];b.noSelection=!0;b.createdNodes=[];b.zId=0;b._ver=(new Date).getTime()}],beforeA:[],afterA:[],innerBeforeA:[],innerAfterA:[],zTreeTools:[]},f={addNodeCache:function(a,b){f.getCache(a).nodes[f.getNodeCacheId(b.tId)]=b},getNodeCacheId:function(a){return a.substring(a.lastIndexOf("_")+
1)},addAfterA:function(a){h.afterA.push(a)},addBeforeA:function(a){h.beforeA.push(a)},addInnerAfterA:function(a){h.innerAfterA.push(a)},addInnerBeforeA:function(a){h.innerBeforeA.push(a)},addInitBind:function(a){h.bind.push(a)},addInitUnBind:function(a){h.unbind.push(a)},addInitCache:function(a){h.caches.push(a)},addInitNode:function(a){h.nodes.push(a)},addInitProxy:function(a,b){b?h.proxys.splice(0,0,a):h.proxys.push(a)},addInitRoot:function(a){h.roots.push(a)},addNodesData:function(a,b,c){var e=
a.data.key.children;b[e]||(b[e]=[]);if(b[e].length>0)b[e][b[e].length-1].isLastNode=!1,j.setNodeLineIcos(a,b[e][b[e].length-1]);b.isParent=!0;b[e]=b[e].concat(c)},addSelectedNode:function(a,b){var c=f.getRoot(a);f.isSelectedNode(a,b)||c.curSelectedList.push(b)},addCreatedNode:function(a,b){(a.callback.onNodeCreated||a.view.addDiyDom)&&f.getRoot(a).createdNodes.push(b)},addZTreeTools:function(a){h.zTreeTools.push(a)},exSetting:function(a){p.extend(!0,l,a)},fixPIdKeyValue:function(a,b){a.data.simpleData.enable&&
(b[a.data.simpleData.pIdKey]=b.parentTId?b.getParentNode()[a.data.simpleData.idKey]:a.data.simpleData.rootPId)},getAfterA:function(){for(var a=0,b=h.afterA.length;a<b;a++)h.afterA[a].apply(this,arguments)},getBeforeA:function(){for(var a=0,b=h.beforeA.length;a<b;a++)h.beforeA[a].apply(this,arguments)},getInnerAfterA:function(){for(var a=0,b=h.innerAfterA.length;a<b;a++)h.innerAfterA[a].apply(this,arguments)},getInnerBeforeA:function(){for(var a=0,b=h.innerBeforeA.length;a<b;a++)h.innerBeforeA[a].apply(this,
arguments)},getCache:function(a){return q[a.treeId]},getNextNode:function(a,b){if(!b)return null;for(var c=a.data.key.children,e=b.parentTId?b.getParentNode():f.getRoot(a),d=0,m=e[c].length-1;d<=m;d++)if(e[c][d]===b)return d==m?null:e[c][d+1];return null},getNodeByParam:function(a,b,c,e){if(!b||!c)return null;for(var d=a.data.key.children,m=0,g=b.length;m<g;m++){if(b[m][c]==e)return b[m];var i=f.getNodeByParam(a,b[m][d],c,e);if(i)return i}return null},getNodeCache:function(a,b){if(!b)return null;
var c=q[a.treeId].nodes[f.getNodeCacheId(b)];return c?c:null},getNodeName:function(a,b){return""+b[a.data.key.name]},getNodeTitle:function(a,b){return""+b[a.data.key.title===""?a.data.key.name:a.data.key.title]},getNodes:function(a){return f.getRoot(a)[a.data.key.children]},getNodesByParam:function(a,b,c,e){if(!b||!c)return[];for(var d=a.data.key.children,m=[],g=0,i=b.length;g<i;g++)b[g][c]==e&&m.push(b[g]),m=m.concat(f.getNodesByParam(a,b[g][d],c,e));return m},getNodesByParamFuzzy:function(a,b,c,
e){if(!b||!c)return[];for(var d=a.data.key.children,m=[],e=e.toLowerCase(),g=0,i=b.length;g<i;g++)typeof b[g][c]=="string"&&b[g][c].toLowerCase().indexOf(e)>-1&&m.push(b[g]),m=m.concat(f.getNodesByParamFuzzy(a,b[g][d],c,e));return m},getNodesByFilter:function(a,b,c,e,d){if(!b)return e?null:[];for(var m=a.data.key.children,g=e?null:[],i=0,h=b.length;i<h;i++){if(k.apply(c,[b[i],d],!1)){if(e)return b[i];g.push(b[i])}var j=f.getNodesByFilter(a,b[i][m],c,e,d);if(e&&j)return j;g=e?j:g.concat(j)}return g},
getPreNode:function(a,b){if(!b)return null;for(var c=a.data.key.children,e=b.parentTId?b.getParentNode():f.getRoot(a),d=0,m=e[c].length;d<m;d++)if(e[c][d]===b)return d==0?null:e[c][d-1];return null},getRoot:function(a){return a?t[a.treeId]:null},getRoots:function(){return t},getSetting:function(a){return s[a]},getSettings:function(){return s},getZTreeTools:function(a){return(a=this.getRoot(this.getSetting(a)))?a.treeTools:null},initCache:function(){for(var a=0,b=h.caches.length;a<b;a++)h.caches[a].apply(this,
arguments)},initNode:function(){for(var a=0,b=h.nodes.length;a<b;a++)h.nodes[a].apply(this,arguments)},initRoot:function(){for(var a=0,b=h.roots.length;a<b;a++)h.roots[a].apply(this,arguments)},isSelectedNode:function(a,b){for(var c=f.getRoot(a),e=0,d=c.curSelectedList.length;e<d;e++)if(b===c.curSelectedList[e])return!0;return!1},removeNodeCache:function(a,b){var c=a.data.key.children;if(b[c])for(var e=0,d=b[c].length;e<d;e++)arguments.callee(a,b[c][e]);f.getCache(a).nodes[f.getNodeCacheId(b.tId)]=
null},removeSelectedNode:function(a,b){for(var c=f.getRoot(a),e=0,d=c.curSelectedList.length;e<d;e++)if(b===c.curSelectedList[e]||!f.getNodeCache(a,c.curSelectedList[e].tId))c.curSelectedList.splice(e,1),e--,d--},setCache:function(a,b){q[a.treeId]=b},setRoot:function(a,b){t[a.treeId]=b},setZTreeTools:function(){for(var a=0,b=h.zTreeTools.length;a<b;a++)h.zTreeTools[a].apply(this,arguments)},transformToArrayFormat:function(a,b){if(!b)return[];var c=a.data.key.children,e=[];if(k.isArray(b))for(var d=
0,m=b.length;d<m;d++)e.push(b[d]),b[d][c]&&(e=e.concat(f.transformToArrayFormat(a,b[d][c])));else e.push(b),b[c]&&(e=e.concat(f.transformToArrayFormat(a,b[c])));return e},transformTozTreeFormat:function(a,b){var c,e,d=a.data.simpleData.idKey,m=a.data.simpleData.pIdKey,g=a.data.key.children;if(!d||d==""||!b)return[];if(k.isArray(b)){var f=[],i=[];c=0;for(e=b.length;c<e;c++)i[b[c][d]]=b[c];c=0;for(e=b.length;c<e;c++)i[b[c][m]]&&b[c][d]!=b[c][m]?(i[b[c][m]][g]||(i[b[c][m]][g]=[]),i[b[c][m]][g].push(b[c])):
f.push(b[c]);return f}else return[b]}},g={bindEvent:function(){for(var a=0,b=h.bind.length;a<b;a++)h.bind[a].apply(this,arguments)},unbindEvent:function(){for(var a=0,b=h.unbind.length;a<b;a++)h.unbind[a].apply(this,arguments)},bindTree:function(a){var b={treeId:a.treeId},c=a.treeObj;a.view.txtSelectedEnable||c.bind("selectstart",function(b){b=b.originalEvent.srcElement.nodeName.toLowerCase();return b==="input"||b==="textarea"}).css({"-moz-user-select":"-moz-none"});c.bind("click",b,g.proxy);c.bind("dblclick",
b,g.proxy);c.bind("mouseover",b,g.proxy);c.bind("mouseout",b,g.proxy);c.bind("mousedown",b,g.proxy);c.bind("mouseup",b,g.proxy);c.bind("contextmenu",b,g.proxy)},unbindTree:function(a){a.treeObj.unbind("click",g.proxy).unbind("dblclick",g.proxy).unbind("mouseover",g.proxy).unbind("mouseout",g.proxy).unbind("mousedown",g.proxy).unbind("mouseup",g.proxy).unbind("contextmenu",g.proxy)},doProxy:function(){for(var a=[],b=0,c=h.proxys.length;b<c;b++){var e=h.proxys[b].apply(this,arguments);a.push(e);if(e.stop)break}return a},
proxy:function(a){var b=f.getSetting(a.data.treeId);if(!k.uCanDo(b,a))return!0;for(var b=g.doProxy(a),c=!0,e=0,d=b.length;e<d;e++){var m=b[e];m.nodeEventCallback&&(c=m.nodeEventCallback.apply(m,[a,m.node])&&c);m.treeEventCallback&&(c=m.treeEventCallback.apply(m,[a,m.node])&&c)}return c}},n={onSwitchNode:function(a,b){var c=f.getSetting(a.data.treeId);if(b.open){if(k.apply(c.callback.beforeCollapse,[c.treeId,b],!0)==!1)return!0}else if(k.apply(c.callback.beforeExpand,[c.treeId,b],!0)==!1)return!0;
f.getRoot(c).expandTriggerFlag=!0;j.switchNode(c,b);return!0},onClickNode:function(a,b){var c=f.getSetting(a.data.treeId),e=c.view.autoCancelSelected&&(a.ctrlKey||a.metaKey)&&f.isSelectedNode(c,b)?0:c.view.autoCancelSelected&&(a.ctrlKey||a.metaKey)&&c.view.selectedMulti?2:1;if(k.apply(c.callback.beforeClick,[c.treeId,b,e],!0)==!1)return!0;e===0?j.cancelPreSelectedNode(c,b):j.selectNode(c,b,e===2);c.treeObj.trigger(d.event.CLICK,[a,c.treeId,b,e]);return!0},onZTreeMousedown:function(a,b){var c=f.getSetting(a.data.treeId);
k.apply(c.callback.beforeMouseDown,[c.treeId,b],!0)&&k.apply(c.callback.onMouseDown,[a,c.treeId,b]);return!0},onZTreeMouseup:function(a,b){var c=f.getSetting(a.data.treeId);k.apply(c.callback.beforeMouseUp,[c.treeId,b],!0)&&k.apply(c.callback.onMouseUp,[a,c.treeId,b]);return!0},onZTreeDblclick:function(a,b){var c=f.getSetting(a.data.treeId);k.apply(c.callback.beforeDblClick,[c.treeId,b],!0)&&k.apply(c.callback.onDblClick,[a,c.treeId,b]);return!0},onZTreeContextmenu:function(a,b){var c=f.getSetting(a.data.treeId);
k.apply(c.callback.beforeRightClick,[c.treeId,b],!0)&&k.apply(c.callback.onRightClick,[a,c.treeId,b]);return typeof c.callback.onRightClick!="function"}},k={apply:function(a,b,c){if(typeof a=="function")return a.apply(u,b?b:[]);return c},canAsync:function(a,b){var c=a.data.key.children;return a.async.enable&&b&&b.isParent&&!(b.zAsync||b[c]&&b[c].length>0)},clone:function(a){if(a===null)return null;var b=k.isArray(a)?[]:{},c;for(c in a)b[c]=a[c]instanceof Date?new Date(a[c].getTime()):typeof a[c]===
"object"?arguments.callee(a[c]):a[c];return b},eqs:function(a,b){return a.toLowerCase()===b.toLowerCase()},isArray:function(a){return Object.prototype.toString.apply(a)==="[object Array]"},$:function(a,b,c){b&&typeof b!="string"&&(c=b,b="");return typeof a=="string"?p(a,c?c.treeObj.get(0).ownerDocument:null):p("#"+a.tId+b,c?c.treeObj:null)},getMDom:function(a,b,c){if(!b)return null;for(;b&&b.id!==a.treeId;){for(var e=0,d=c.length;b.tagName&&e<d;e++)if(k.eqs(b.tagName,c[e].tagName)&&b.getAttribute(c[e].attrName)!==
null)return b;b=b.parentNode}return null},getNodeMainDom:function(a){return p(a).parent("li").get(0)||p(a).parentsUntil("li").parent().get(0)},isChildOrSelf:function(a,b){return p(a).closest("#"+b).length>0},uCanDo:function(){return!0}},j={addNodes:function(a,b,c,e){if(!a.data.keep.leaf||!b||b.isParent)if(k.isArray(c)||(c=[c]),a.data.simpleData.enable&&(c=f.transformTozTreeFormat(a,c)),b){var o=i(b,d.id.SWITCH,a),m=i(b,d.id.ICON,a),g=i(b,d.id.UL,a);if(!b.open)j.replaceSwitchClass(b,o,d.folder.CLOSE),
j.replaceIcoClass(b,m,d.folder.CLOSE),b.open=!1,g.css({display:"none"});f.addNodesData(a,b,c);j.createNodes(a,b.level+1,c,b);e||j.expandCollapseParentNode(a,b,!0)}else f.addNodesData(a,f.getRoot(a),c),j.createNodes(a,0,c,null)},appendNodes:function(a,b,c,e,d,m){if(!c)return[];for(var g=[],i=a.data.key.children,h=0,k=c.length;h<k;h++){var n=c[h];if(d){var l=(e?e:f.getRoot(a))[i].length==c.length&&h==0;f.initNode(a,b,n,e,l,h==c.length-1,m);f.addNodeCache(a,n)}l=[];n[i]&&n[i].length>0&&(l=j.appendNodes(a,
b+1,n[i],n,d,m&&n.open));m&&(j.makeDOMNodeMainBefore(g,a,n),j.makeDOMNodeLine(g,a,n),f.getBeforeA(a,n,g),j.makeDOMNodeNameBefore(g,a,n),f.getInnerBeforeA(a,n,g),j.makeDOMNodeIcon(g,a,n),f.getInnerAfterA(a,n,g),j.makeDOMNodeNameAfter(g,a,n),f.getAfterA(a,n,g),n.isParent&&n.open&&j.makeUlHtml(a,n,g,l.join("")),j.makeDOMNodeMainAfter(g,a,n),f.addCreatedNode(a,n))}return g},appendParentULDom:function(a,b){var c=[],e=i(b,a);!e.get(0)&&b.parentTId&&(j.appendParentULDom(a,b.getParentNode()),e=i(b,a));var o=
i(b,d.id.UL,a);o.get(0)&&o.remove();o=j.appendNodes(a,b.level+1,b[a.data.key.children],b,!1,!0);j.makeUlHtml(a,b,c,o.join(""));e.append(c.join(""))},asyncNode:function(a,b,c,e){var o,m;if(b&&!b.isParent)return k.apply(e),!1;else if(b&&b.isAjaxing)return!1;else if(k.apply(a.callback.beforeAsync,[a.treeId,b],!0)==!1)return k.apply(e),!1;if(b)b.isAjaxing=!0,i(b,d.id.ICON,a).attr({style:"","class":d.className.BUTTON+" "+d.className.ICO_LOADING});var g={};o=0;for(m=a.async.autoParam.length;b&&o<m;o++){var h=
a.async.autoParam[o].split("="),n=h;h.length>1&&(n=h[1],h=h[0]);g[n]=b[h]}if(k.isArray(a.async.otherParam)){o=0;for(m=a.async.otherParam.length;o<m;o+=2)g[a.async.otherParam[o]]=a.async.otherParam[o+1]}else for(var l in a.async.otherParam)g[l]=a.async.otherParam[l];var u=f.getRoot(a)._ver;p.ajax({contentType:a.async.contentType,cache:!1,type:a.async.type,url:k.apply(a.async.url,[a.treeId,b],a.async.url),data:g,dataType:a.async.dataType,success:function(o){if(u==f.getRoot(a)._ver){var m=[];try{m=!o||
o.length==0?[]:typeof o=="string"?eval("("+o+")"):o}catch(g){m=o}if(b)b.isAjaxing=null,b.zAsync=!0;j.setNodeLineIcos(a,b);m&&m!==""?(m=k.apply(a.async.dataFilter,[a.treeId,b,m],m),j.addNodes(a,b,m?k.clone(m):[],!!c)):j.addNodes(a,b,[],!!c);a.treeObj.trigger(d.event.ASYNC_SUCCESS,[a.treeId,b,o]);k.apply(e)}},error:function(c,e,o){if(u==f.getRoot(a)._ver){if(b)b.isAjaxing=null;j.setNodeLineIcos(a,b);a.treeObj.trigger(d.event.ASYNC_ERROR,[a.treeId,b,c,e,o])}}});return!0},cancelPreSelectedNode:function(a,
b){for(var c=f.getRoot(a).curSelectedList,e=c.length-1;e>=0;e--)if(!b||b===c[e])if(i(c[e],d.id.A,a).removeClass(d.node.CURSELECTED),b){f.removeSelectedNode(a,b);break}if(!b)f.getRoot(a).curSelectedList=[]},createNodeCallback:function(a){if(a.callback.onNodeCreated||a.view.addDiyDom)for(var b=f.getRoot(a);b.createdNodes.length>0;){var c=b.createdNodes.shift();k.apply(a.view.addDiyDom,[a.treeId,c]);a.callback.onNodeCreated&&a.treeObj.trigger(d.event.NODECREATED,[a.treeId,c])}},createNodes:function(a,
b,c,e){if(c&&c.length!=0){var o=f.getRoot(a),m=a.data.key.children,m=!e||e.open||!!i(e[m][0],a).get(0);o.createdNodes=[];b=j.appendNodes(a,b,c,e,!0,m);e?(e=i(e,d.id.UL,a),e.get(0)&&e.append(b.join(""))):a.treeObj.append(b.join(""));j.createNodeCallback(a)}},destroy:function(a){a&&(f.initCache(a),f.initRoot(a),g.unbindTree(a),g.unbindEvent(a),a.treeObj.empty(),delete s[a.treeId])},expandCollapseNode:function(a,b,c,e,o){var m=f.getRoot(a),g=a.data.key.children;if(b){if(m.expandTriggerFlag){var h=o,
o=function(){h&&h();b.open?a.treeObj.trigger(d.event.EXPAND,[a.treeId,b]):a.treeObj.trigger(d.event.COLLAPSE,[a.treeId,b])};m.expandTriggerFlag=!1}if(!b.open&&b.isParent&&(!i(b,d.id.UL,a).get(0)||b[g]&&b[g].length>0&&!i(b[g][0],a).get(0)))j.appendParentULDom(a,b),j.createNodeCallback(a);if(b.open==c)k.apply(o,[]);else{var c=i(b,d.id.UL,a),m=i(b,d.id.SWITCH,a),n=i(b,d.id.ICON,a);b.isParent?(b.open=!b.open,b.iconOpen&&b.iconClose&&n.attr("style",j.makeNodeIcoStyle(a,b)),b.open?(j.replaceSwitchClass(b,
m,d.folder.OPEN),j.replaceIcoClass(b,n,d.folder.OPEN),e==!1||a.view.expandSpeed==""?(c.show(),k.apply(o,[])):b[g]&&b[g].length>0?c.slideDown(a.view.expandSpeed,o):(c.show(),k.apply(o,[]))):(j.replaceSwitchClass(b,m,d.folder.CLOSE),j.replaceIcoClass(b,n,d.folder.CLOSE),e==!1||a.view.expandSpeed==""||!(b[g]&&b[g].length>0)?(c.hide(),k.apply(o,[])):c.slideUp(a.view.expandSpeed,o))):k.apply(o,[])}}else k.apply(o,[])},expandCollapseParentNode:function(a,b,c,e,d){b&&(b.parentTId?(j.expandCollapseNode(a,
b,c,e),b.parentTId&&j.expandCollapseParentNode(a,b.getParentNode(),c,e,d)):j.expandCollapseNode(a,b,c,e,d))},expandCollapseSonNode:function(a,b,c,e,d){var m=f.getRoot(a),g=a.data.key.children,m=b?b[g]:m[g],g=b?!1:e,i=f.getRoot(a).expandTriggerFlag;f.getRoot(a).expandTriggerFlag=!1;if(m)for(var h=0,n=m.length;h<n;h++)m[h]&&j.expandCollapseSonNode(a,m[h],c,g);f.getRoot(a).expandTriggerFlag=i;j.expandCollapseNode(a,b,c,e,d)},makeDOMNodeIcon:function(a,b,c){var e=f.getNodeName(b,c),e=b.view.nameIsHTML?
e:e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");a.push("<span id='",c.tId,d.id.ICON,"' title='' treeNode",d.id.ICON," class='",j.makeNodeIcoClass(b,c),"' style='",j.makeNodeIcoStyle(b,c),"'></span><span id='",c.tId,d.id.SPAN,"'>",e,"</span>")},makeDOMNodeLine:function(a,b,c){a.push("<span id='",c.tId,d.id.SWITCH,"' title='' class='",j.makeNodeLineClass(b,c),"' treeNode",d.id.SWITCH,"></span>")},makeDOMNodeMainAfter:function(a){a.push("</li>")},makeDOMNodeMainBefore:function(a,
b,c){a.push("<li id='",c.tId,"' class='",d.className.LEVEL,c.level,"' tabindex='0' hidefocus='true' treenode>")},makeDOMNodeNameAfter:function(a){a.push("</a>")},makeDOMNodeNameBefore:function(a,b,c){var e=f.getNodeTitle(b,c),o=j.makeNodeUrl(b,c),m=j.makeNodeFontCss(b,c),g=[],i;for(i in m)g.push(i,":",m[i],";");a.push("<a id='",c.tId,d.id.A,"' class='",d.className.LEVEL,c.level,"' treeNode",d.id.A,' onclick="',c.click||"",'" ',o!=null&&o.length>0?"href='"+o+"'":""," target='",j.makeNodeTarget(c),
"' style='",g.join(""),"'");k.apply(b.view.showTitle,[b.treeId,c],b.view.showTitle)&&e&&a.push("title='",e.replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;"),"'");a.push(">")},makeNodeFontCss:function(a,b){var c=k.apply(a.view.fontCss,[a.treeId,b],a.view.fontCss);return c&&typeof c!="function"?c:{}},makeNodeIcoClass:function(a,b){var c=["ico"];b.isAjaxing||(c[0]=(b.iconSkin?b.iconSkin+"_":"")+c[0],b.isParent?c.push(b.open?d.folder.OPEN:d.folder.CLOSE):c.push(d.folder.DOCU));return d.className.BUTTON+
" "+c.join("_")},makeNodeIcoStyle:function(a,b){var c=[];if(!b.isAjaxing){var e=b.isParent&&b.iconOpen&&b.iconClose?b.open?b.iconOpen:b.iconClose:b.icon;e&&c.push("background:url(",e,") 0 0 no-repeat;");(a.view.showIcon==!1||!k.apply(a.view.showIcon,[a.treeId,b],!0))&&c.push("width:0px;height:0px;")}return c.join("")},makeNodeLineClass:function(a,b){var c=[];a.view.showLine?b.level==0&&b.isFirstNode&&b.isLastNode?c.push(d.line.ROOT):b.level==0&&b.isFirstNode?c.push(d.line.ROOTS):b.isLastNode?c.push(d.line.BOTTOM):
c.push(d.line.CENTER):c.push(d.line.NOLINE);b.isParent?c.push(b.open?d.folder.OPEN:d.folder.CLOSE):c.push(d.folder.DOCU);return j.makeNodeLineClassEx(b)+c.join("_")},makeNodeLineClassEx:function(a){return d.className.BUTTON+" "+d.className.LEVEL+a.level+" "+d.className.SWITCH+" "},makeNodeTarget:function(a){return a.target||"_blank"},makeNodeUrl:function(a,b){var c=a.data.key.url;return b[c]?b[c]:null},makeUlHtml:function(a,b,c,e){c.push("<ul id='",b.tId,d.id.UL,"' class='",d.className.LEVEL,b.level,
" ",j.makeUlLineClass(a,b),"' style='display:",b.open?"block":"none","'>");c.push(e);c.push("</ul>")},makeUlLineClass:function(a,b){return a.view.showLine&&!b.isLastNode?d.line.LINE:""},removeChildNodes:function(a,b){if(b){var c=a.data.key.children,e=b[c];if(e){for(var o=0,m=e.length;o<m;o++)f.removeNodeCache(a,e[o]);f.removeSelectedNode(a);delete b[c];a.data.keep.parent?i(b,d.id.UL,a).empty():(b.isParent=!1,b.open=!1,c=i(b,d.id.SWITCH,a),e=i(b,d.id.ICON,a),j.replaceSwitchClass(b,c,d.folder.DOCU),
j.replaceIcoClass(b,e,d.folder.DOCU),i(b,d.id.UL,a).remove())}}},setFirstNode:function(a,b){var c=a.data.key.children;if(b[c].length>0)b[c][0].isFirstNode=!0},setLastNode:function(a,b){var c=a.data.key.children,e=b[c].length;if(e>0)b[c][e-1].isLastNode=!0},removeNode:function(a,b){var c=f.getRoot(a),e=a.data.key.children,o=b.parentTId?b.getParentNode():c;b.isFirstNode=!1;b.isLastNode=!1;b.getPreNode=function(){return null};b.getNextNode=function(){return null};if(f.getNodeCache(a,b.tId)){i(b,a).remove();
f.removeNodeCache(a,b);f.removeSelectedNode(a,b);for(var m=0,g=o[e].length;m<g;m++)if(o[e][m].tId==b.tId){o[e].splice(m,1);break}j.setFirstNode(a,o);j.setLastNode(a,o);var h,m=o[e].length;if(!a.data.keep.parent&&m==0)o.isParent=!1,o.open=!1,m=i(o,d.id.UL,a),g=i(o,d.id.SWITCH,a),h=i(o,d.id.ICON,a),j.replaceSwitchClass(o,g,d.folder.DOCU),j.replaceIcoClass(o,h,d.folder.DOCU),m.css("display","none");else if(a.view.showLine&&m>0){var n=o[e][m-1],m=i(n,d.id.UL,a),g=i(n,d.id.SWITCH,a);h=i(n,d.id.ICON,a);
o==c?o[e].length==1?j.replaceSwitchClass(n,g,d.line.ROOT):(c=i(o[e][0],d.id.SWITCH,a),j.replaceSwitchClass(o[e][0],c,d.line.ROOTS),j.replaceSwitchClass(n,g,d.line.BOTTOM)):j.replaceSwitchClass(n,g,d.line.BOTTOM);m.removeClass(d.line.LINE)}}},replaceIcoClass:function(a,b,c){if(b&&!a.isAjaxing&&(a=b.attr("class"),a!=void 0)){a=a.split("_");switch(c){case d.folder.OPEN:case d.folder.CLOSE:case d.folder.DOCU:a[a.length-1]=c}b.attr("class",a.join("_"))}},replaceSwitchClass:function(a,b,c){if(b){var e=
b.attr("class");if(e!=void 0){e=e.split("_");switch(c){case d.line.ROOT:case d.line.ROOTS:case d.line.CENTER:case d.line.BOTTOM:case d.line.NOLINE:e[0]=j.makeNodeLineClassEx(a)+c;break;case d.folder.OPEN:case d.folder.CLOSE:case d.folder.DOCU:e[1]=c}b.attr("class",e.join("_"));c!==d.folder.DOCU?b.removeAttr("disabled"):b.attr("disabled","disabled")}}},selectNode:function(a,b,c){c||j.cancelPreSelectedNode(a);i(b,d.id.A,a).addClass(d.node.CURSELECTED);f.addSelectedNode(a,b)},setNodeFontCss:function(a,
b){var c=i(b,d.id.A,a),e=j.makeNodeFontCss(a,b);e&&c.css(e)},setNodeLineIcos:function(a,b){if(b){var c=i(b,d.id.SWITCH,a),e=i(b,d.id.UL,a),o=i(b,d.id.ICON,a),m=j.makeUlLineClass(a,b);m.length==0?e.removeClass(d.line.LINE):e.addClass(m);c.attr("class",j.makeNodeLineClass(a,b));b.isParent?c.removeAttr("disabled"):c.attr("disabled","disabled");o.removeAttr("style");o.attr("style",j.makeNodeIcoStyle(a,b));o.attr("class",j.makeNodeIcoClass(a,b))}},setNodeName:function(a,b){var c=f.getNodeTitle(a,b),e=
i(b,d.id.SPAN,a);e.empty();a.view.nameIsHTML?e.html(f.getNodeName(a,b)):e.text(f.getNodeName(a,b));k.apply(a.view.showTitle,[a.treeId,b],a.view.showTitle)&&i(b,d.id.A,a).attr("title",!c?"":c)},setNodeTarget:function(a,b){i(b,d.id.A,a).attr("target",j.makeNodeTarget(b))},setNodeUrl:function(a,b){var c=i(b,d.id.A,a),e=j.makeNodeUrl(a,b);e==null||e.length==0?c.removeAttr("href"):c.attr("href",e)},switchNode:function(a,b){b.open||!k.canAsync(a,b)?j.expandCollapseNode(a,b,!b.open):a.async.enable?j.asyncNode(a,
b)||j.expandCollapseNode(a,b,!b.open):b&&j.expandCollapseNode(a,b,!b.open)}};p.fn.zTree={consts:{className:{BUTTON:"button",LEVEL:"level",ICO_LOADING:"ico_loading",SWITCH:"switch"},event:{NODECREATED:"ztree_nodeCreated",CLICK:"ztree_click",EXPAND:"ztree_expand",COLLAPSE:"ztree_collapse",ASYNC_SUCCESS:"ztree_async_success",ASYNC_ERROR:"ztree_async_error",REMOVE:"ztree_remove"},id:{A:"_a",ICON:"_ico",SPAN:"_span",SWITCH:"_switch",UL:"_ul"},line:{ROOT:"root",ROOTS:"roots",CENTER:"center",BOTTOM:"bottom",
NOLINE:"noline",LINE:"line"},folder:{OPEN:"open",CLOSE:"close",DOCU:"docu"},node:{CURSELECTED:"curSelectedNode"}},_z:{tools:k,view:j,event:g,data:f,handler:n},getZTreeObj:function(a){return(a=f.getZTreeTools(a))?a:null},destroy:function(a){if(a&&a.length>0)j.destroy(f.getSetting(a));else for(var b in s)j.destroy(s[b])},init:function(a,b,c){var e=k.clone(l);p.extend(!0,e,b);e.treeId=a.attr("id");e.treeObj=a;e.treeObj.empty();s[e.treeId]=e;if(typeof document.body.style.maxHeight==="undefined")e.view.expandSpeed=
"";f.initRoot(e);a=f.getRoot(e);b=e.data.key.children;c=c?k.clone(k.isArray(c)?c:[c]):[];a[b]=e.data.simpleData.enable?f.transformTozTreeFormat(e,c):c;f.initCache(e);g.unbindTree(e);g.bindTree(e);g.unbindEvent(e);g.bindEvent(e);c={setting:e,addNodes:function(b,a,c){function d(){j.addNodes(e,b,g,c==!0)}if(!a)return null;b||(b=null);if(b&&!b.isParent&&e.data.keep.leaf)return null;var g=k.clone(k.isArray(a)?a:[a]);k.canAsync(e,b)?j.asyncNode(e,b,c,d):d();return g},cancelSelectedNode:function(b){j.cancelPreSelectedNode(e,
b)},destroy:function(){j.destroy(e)},expandAll:function(b){b=!!b;j.expandCollapseSonNode(e,null,b,!0);return b},expandNode:function(b,a,c,d,g){if(!b||!b.isParent)return null;a!==!0&&a!==!1&&(a=!b.open);if((g=!!g)&&a&&k.apply(e.callback.beforeExpand,[e.treeId,b],!0)==!1)return null;else if(g&&!a&&k.apply(e.callback.beforeCollapse,[e.treeId,b],!0)==!1)return null;a&&b.parentTId&&j.expandCollapseParentNode(e,b.getParentNode(),a,!1);if(a===b.open&&!c)return null;f.getRoot(e).expandTriggerFlag=g;if(!k.canAsync(e,
b)&&c)j.expandCollapseSonNode(e,b,a,!0,function(){if(d!==!1)try{i(b,e).focus().blur()}catch(a){}});else if(b.open=!a,j.switchNode(this.setting,b),d!==!1)try{i(b,e).focus().blur()}catch(h){}return a},getNodes:function(){return f.getNodes(e)},getNodeByParam:function(b,a,c){if(!b)return null;return f.getNodeByParam(e,c?c[e.data.key.children]:f.getNodes(e),b,a)},getNodeByTId:function(b){return f.getNodeCache(e,b)},getNodesByParam:function(b,a,c){if(!b)return null;return f.getNodesByParam(e,c?c[e.data.key.children]:
f.getNodes(e),b,a)},getNodesByParamFuzzy:function(b,a,c){if(!b)return null;return f.getNodesByParamFuzzy(e,c?c[e.data.key.children]:f.getNodes(e),b,a)},getNodesByFilter:function(b,a,c,d){a=!!a;if(!b||typeof b!="function")return a?null:[];return f.getNodesByFilter(e,c?c[e.data.key.children]:f.getNodes(e),b,a,d)},getNodeIndex:function(b){if(!b)return null;for(var a=e.data.key.children,c=b.parentTId?b.getParentNode():f.getRoot(e),d=0,g=c[a].length;d<g;d++)if(c[a][d]==b)return d;return-1},getSelectedNodes:function(){for(var b=
[],a=f.getRoot(e).curSelectedList,c=0,d=a.length;c<d;c++)b.push(a[c]);return b},isSelectedNode:function(b){return f.isSelectedNode(e,b)},reAsyncChildNodes:function(b,a,c){if(this.setting.async.enable){var g=!b;g&&(b=f.getRoot(e));if(a=="refresh"){for(var a=this.setting.data.key.children,h=0,n=b[a]?b[a].length:0;h<n;h++)f.removeNodeCache(e,b[a][h]);f.removeSelectedNode(e);b[a]=[];g?this.setting.treeObj.empty():i(b,d.id.UL,e).empty()}j.asyncNode(this.setting,g?null:b,!!c)}},refresh:function(){this.setting.treeObj.empty();
var b=f.getRoot(e),a=b[e.data.key.children];f.initRoot(e);b[e.data.key.children]=a;f.initCache(e);j.createNodes(e,0,b[e.data.key.children])},removeChildNodes:function(b){if(!b)return null;var a=b[e.data.key.children];j.removeChildNodes(e,b);return a?a:null},removeNode:function(b,a){b&&(a=!!a,a&&k.apply(e.callback.beforeRemove,[e.treeId,b],!0)==!1||(j.removeNode(e,b),a&&this.setting.treeObj.trigger(d.event.REMOVE,[e.treeId,b])))},selectNode:function(b,a){if(b&&k.uCanDo(e)){a=e.view.selectedMulti&&
a;if(b.parentTId)j.expandCollapseParentNode(e,b.getParentNode(),!0,!1,function(){try{i(b,e).focus().blur()}catch(a){}});else try{i(b,e).focus().blur()}catch(c){}j.selectNode(e,b,a)}},transformTozTreeNodes:function(b){return f.transformTozTreeFormat(e,b)},transformToArray:function(b){return f.transformToArrayFormat(e,b)},updateNode:function(b){b&&i(b,e).get(0)&&k.uCanDo(e)&&(j.setNodeName(e,b),j.setNodeTarget(e,b),j.setNodeUrl(e,b),j.setNodeLineIcos(e,b),j.setNodeFontCss(e,b))}};a.treeTools=c;f.setZTreeTools(e,
c);a[b]&&a[b].length>0?j.createNodes(e,0,a[b]):e.async.enable&&e.async.url&&e.async.url!==""&&j.asyncNode(e);return c}};var u=p.fn.zTree,i=k.$,d=u.consts})(jQuery);
(function(p){var s={event:{CHECK:"ztree_check"},id:{CHECK:"_check"},checkbox:{STYLE:"checkbox",DEFAULT:"chk",DISABLED:"disable",FALSE:"false",TRUE:"true",FULL:"full",PART:"part",FOCUS:"focus"},radio:{STYLE:"radio",TYPE_ALL:"all",TYPE_LEVEL:"level"}},t={check:{enable:!1,autoCheckTrigger:!1,chkStyle:s.checkbox.STYLE,nocheckInherit:!1,chkDisabledInherit:!1,radioType:s.radio.TYPE_LEVEL,chkboxType:{Y:"ps",N:"ps"}},data:{key:{checked:"checked"}},callback:{beforeCheck:null,onCheck:null}},q={onCheckNode:function(i,
d){if(d.chkDisabled===!0)return!1;var a=g.getSetting(i.data.treeId),b=a.data.key.checked;if(l.apply(a.callback.beforeCheck,[a.treeId,d],!0)==!1)return!0;d[b]=!d[b];f.checkNodeRelation(a,d);b=n(d,h.id.CHECK,a);f.setChkClass(a,b,d);f.repairParentChkClassWithSelf(a,d);a.treeObj.trigger(h.event.CHECK,[i,a.treeId,d]);return!0},onMouseoverCheck:function(i,d){if(d.chkDisabled===!0)return!1;var a=g.getSetting(i.data.treeId),b=n(d,h.id.CHECK,a);d.check_Focus=!0;f.setChkClass(a,b,d);return!0},onMouseoutCheck:function(i,
d){if(d.chkDisabled===!0)return!1;var a=g.getSetting(i.data.treeId),b=n(d,h.id.CHECK,a);d.check_Focus=!1;f.setChkClass(a,b,d);return!0}};p.extend(!0,p.fn.zTree.consts,s);p.extend(!0,p.fn.zTree._z,{tools:{},view:{checkNodeRelation:function(i,d){var a,b,c,e=i.data.key.children,o=i.data.key.checked;a=h.radio;if(i.check.chkStyle==a.STYLE){var m=g.getRadioCheckedList(i);if(d[o])if(i.check.radioType==a.TYPE_ALL){for(b=m.length-1;b>=0;b--)a=m[b],a[o]&&a!=d&&(a[o]=!1,m.splice(b,1),f.setChkClass(i,n(a,h.id.CHECK,
i),a),a.parentTId!=d.parentTId&&f.repairParentChkClassWithSelf(i,a));m.push(d)}else{m=d.parentTId?d.getParentNode():g.getRoot(i);b=0;for(c=m[e].length;b<c;b++)a=m[e][b],a[o]&&a!=d&&(a[o]=!1,f.setChkClass(i,n(a,h.id.CHECK,i),a))}else if(i.check.radioType==a.TYPE_ALL){b=0;for(c=m.length;b<c;b++)if(d==m[b]){m.splice(b,1);break}}}else d[o]&&(!d[e]||d[e].length==0||i.check.chkboxType.Y.indexOf("s")>-1)&&f.setSonNodeCheckBox(i,d,!0),!d[o]&&(!d[e]||d[e].length==0||i.check.chkboxType.N.indexOf("s")>-1)&&
f.setSonNodeCheckBox(i,d,!1),d[o]&&i.check.chkboxType.Y.indexOf("p")>-1&&f.setParentNodeCheckBox(i,d,!0),!d[o]&&i.check.chkboxType.N.indexOf("p")>-1&&f.setParentNodeCheckBox(i,d,!1)},makeChkClass:function(g,d){var a=g.data.key.checked,b=h.checkbox,c=h.radio,e="",e=d.chkDisabled===!0?b.DISABLED:d.halfCheck?b.PART:g.check.chkStyle==c.STYLE?d.check_Child_State<1?b.FULL:b.PART:d[a]?d.check_Child_State===2||d.check_Child_State===-1?b.FULL:b.PART:d.check_Child_State<1?b.FULL:b.PART,a=g.check.chkStyle+"_"+
(d[a]?b.TRUE:b.FALSE)+"_"+e,a=d.check_Focus&&d.chkDisabled!==!0?a+"_"+b.FOCUS:a;return h.className.BUTTON+" "+b.DEFAULT+" "+a},repairAllChk:function(i,d){if(i.check.enable&&i.check.chkStyle===h.checkbox.STYLE)for(var a=i.data.key.checked,b=i.data.key.children,c=g.getRoot(i),e=0,o=c[b].length;e<o;e++){var m=c[b][e];m.nocheck!==!0&&m.chkDisabled!==!0&&(m[a]=d);f.setSonNodeCheckBox(i,m,d)}},repairChkClass:function(i,d){if(d&&(g.makeChkFlag(i,d),d.nocheck!==!0)){var a=n(d,h.id.CHECK,i);f.setChkClass(i,
a,d)}},repairParentChkClass:function(g,d){if(d&&d.parentTId){var a=d.getParentNode();f.repairChkClass(g,a);f.repairParentChkClass(g,a)}},repairParentChkClassWithSelf:function(g,d){if(d){var a=g.data.key.children;d[a]&&d[a].length>0?f.repairParentChkClass(g,d[a][0]):f.repairParentChkClass(g,d)}},repairSonChkDisabled:function(g,d,a,b){if(d){var c=g.data.key.children;if(d.chkDisabled!=a)d.chkDisabled=a;f.repairChkClass(g,d);if(d[c]&&b)for(var e=0,h=d[c].length;e<h;e++)f.repairSonChkDisabled(g,d[c][e],
a,b)}},repairParentChkDisabled:function(g,d,a,b){if(d){if(d.chkDisabled!=a&&b)d.chkDisabled=a;f.repairChkClass(g,d);f.repairParentChkDisabled(g,d.getParentNode(),a,b)}},setChkClass:function(g,d,a){d&&(a.nocheck===!0?d.hide():d.show(),d.attr("class",f.makeChkClass(g,a)))},setParentNodeCheckBox:function(i,d,a,b){var c=i.data.key.children,e=i.data.key.checked,o=n(d,h.id.CHECK,i);b||(b=d);g.makeChkFlag(i,d);d.nocheck!==!0&&d.chkDisabled!==!0&&(d[e]=a,f.setChkClass(i,o,d),i.check.autoCheckTrigger&&d!=
b&&i.treeObj.trigger(h.event.CHECK,[null,i.treeId,d]));if(d.parentTId){o=!0;if(!a)for(var c=d.getParentNode()[c],m=0,j=c.length;m<j;m++)if(c[m].nocheck!==!0&&c[m].chkDisabled!==!0&&c[m][e]||(c[m].nocheck===!0||c[m].chkDisabled===!0)&&c[m].check_Child_State>0){o=!1;break}o&&f.setParentNodeCheckBox(i,d.getParentNode(),a,b)}},setSonNodeCheckBox:function(i,d,a,b){if(d){var c=i.data.key.children,e=i.data.key.checked,o=n(d,h.id.CHECK,i);b||(b=d);var m=!1;if(d[c])for(var j=0,k=d[c].length;j<k&&d.chkDisabled!==
!0;j++){var l=d[c][j];f.setSonNodeCheckBox(i,l,a,b);l.chkDisabled===!0&&(m=!0)}if(d!=g.getRoot(i)&&d.chkDisabled!==!0){m&&d.nocheck!==!0&&g.makeChkFlag(i,d);if(d.nocheck!==!0&&d.chkDisabled!==!0){if(d[e]=a,!m)d.check_Child_State=d[c]&&d[c].length>0?a?2:0:-1}else d.check_Child_State=-1;f.setChkClass(i,o,d);i.check.autoCheckTrigger&&d!=b&&d.nocheck!==!0&&d.chkDisabled!==!0&&i.treeObj.trigger(h.event.CHECK,[null,i.treeId,d])}}}},event:{},data:{getRadioCheckedList:function(f){for(var d=g.getRoot(f).radioCheckedList,
a=0,b=d.length;a<b;a++)g.getNodeCache(f,d[a].tId)||(d.splice(a,1),a--,b--);return d},getCheckStatus:function(g,d){if(!g.check.enable||d.nocheck||d.chkDisabled)return null;var a=g.data.key.checked;return{checked:d[a],half:d.halfCheck?d.halfCheck:g.check.chkStyle==h.radio.STYLE?d.check_Child_State===2:d[a]?d.check_Child_State>-1&&d.check_Child_State<2:d.check_Child_State>0}},getTreeCheckedNodes:function(f,d,a,b){if(!d)return[];for(var c=f.data.key.children,e=f.data.key.checked,o=a&&f.check.chkStyle==
h.radio.STYLE&&f.check.radioType==h.radio.TYPE_ALL,b=!b?[]:b,m=0,n=d.length;m<n;m++){if(d[m].nocheck!==!0&&d[m].chkDisabled!==!0&&d[m][e]==a&&(b.push(d[m]),o))break;g.getTreeCheckedNodes(f,d[m][c],a,b);if(o&&b.length>0)break}return b},getTreeChangeCheckedNodes:function(f,d,a){if(!d)return[];for(var b=f.data.key.children,c=f.data.key.checked,a=!a?[]:a,e=0,h=d.length;e<h;e++)d[e].nocheck!==!0&&d[e].chkDisabled!==!0&&d[e][c]!=d[e].checkedOld&&a.push(d[e]),g.getTreeChangeCheckedNodes(f,d[e][b],a);return a},
makeChkFlag:function(g,d){if(d){var a=g.data.key.children,b=g.data.key.checked,c=-1;if(d[a])for(var e=0,f=d[a].length;e<f;e++){var m=d[a][e],n=-1;if(g.check.chkStyle==h.radio.STYLE)if(n=m.nocheck===!0||m.chkDisabled===!0?m.check_Child_State:m.halfCheck===!0?2:m[b]?2:m.check_Child_State>0?2:0,n==2){c=2;break}else n==0&&(c=0);else if(g.check.chkStyle==h.checkbox.STYLE)if(n=m.nocheck===!0||m.chkDisabled===!0?m.check_Child_State:m.halfCheck===!0?1:m[b]?m.check_Child_State===-1||m.check_Child_State===
2?2:1:m.check_Child_State>0?1:0,n===1){c=1;break}else if(n===2&&c>-1&&e>0&&n!==c){c=1;break}else if(c===2&&n>-1&&n<2){c=1;break}else n>-1&&(c=n)}d.check_Child_State=c}}}});var p=p.fn.zTree,l=p._z.tools,h=p.consts,f=p._z.view,g=p._z.data,n=l.$;g.exSetting(t);g.addInitBind(function(g){g.treeObj.bind(h.event.CHECK,function(d,a,b,c){d.srcEvent=a;l.apply(g.callback.onCheck,[d,b,c])})});g.addInitUnBind(function(g){g.treeObj.unbind(h.event.CHECK)});g.addInitCache(function(){});g.addInitNode(function(f,d,
a,b){if(a){d=f.data.key.checked;typeof a[d]=="string"&&(a[d]=l.eqs(a[d],"true"));a[d]=!!a[d];a.checkedOld=a[d];if(typeof a.nocheck=="string")a.nocheck=l.eqs(a.nocheck,"true");a.nocheck=!!a.nocheck||f.check.nocheckInherit&&b&&!!b.nocheck;if(typeof a.chkDisabled=="string")a.chkDisabled=l.eqs(a.chkDisabled,"true");a.chkDisabled=!!a.chkDisabled||f.check.chkDisabledInherit&&b&&!!b.chkDisabled;if(typeof a.halfCheck=="string")a.halfCheck=l.eqs(a.halfCheck,"true");a.halfCheck=!!a.halfCheck;a.check_Child_State=
-1;a.check_Focus=!1;a.getCheckStatus=function(){return g.getCheckStatus(f,a)};f.check.chkStyle==h.radio.STYLE&&f.check.radioType==h.radio.TYPE_ALL&&a[d]&&g.getRoot(f).radioCheckedList.push(a)}});g.addInitProxy(function(f){var d=f.target,a=g.getSetting(f.data.treeId),b="",c=null,e="",o=null;if(l.eqs(f.type,"mouseover")){if(a.check.enable&&l.eqs(d.tagName,"span")&&d.getAttribute("treeNode"+h.id.CHECK)!==null)b=l.getNodeMainDom(d).id,e="mouseoverCheck"}else if(l.eqs(f.type,"mouseout")){if(a.check.enable&&
l.eqs(d.tagName,"span")&&d.getAttribute("treeNode"+h.id.CHECK)!==null)b=l.getNodeMainDom(d).id,e="mouseoutCheck"}else if(l.eqs(f.type,"click")&&a.check.enable&&l.eqs(d.tagName,"span")&&d.getAttribute("treeNode"+h.id.CHECK)!==null)b=l.getNodeMainDom(d).id,e="checkNode";if(b.length>0)switch(c=g.getNodeCache(a,b),e){case "checkNode":o=q.onCheckNode;break;case "mouseoverCheck":o=q.onMouseoverCheck;break;case "mouseoutCheck":o=q.onMouseoutCheck}return{stop:e==="checkNode",node:c,nodeEventType:e,nodeEventCallback:o,
treeEventType:"",treeEventCallback:null}},!0);g.addInitRoot(function(f){g.getRoot(f).radioCheckedList=[]});g.addBeforeA(function(i,d,a){i.check.enable&&(g.makeChkFlag(i,d),a.push("<span ID='",d.tId,h.id.CHECK,"' class='",f.makeChkClass(i,d),"' treeNode",h.id.CHECK,d.nocheck===!0?" style='display:none;'":"","></span>"))});g.addZTreeTools(function(i,d){d.checkNode=function(b,a,e,d){var g=this.setting.data.key.checked;if(b.chkDisabled!==!0&&(a!==!0&&a!==!1&&(a=!b[g]),d=!!d,(b[g]!==a||e)&&!(d&&l.apply(this.setting.callback.beforeCheck,
[this.setting.treeId,b],!0)==!1)&&l.uCanDo(this.setting)&&this.setting.check.enable&&b.nocheck!==!0))b[g]=a,a=n(b,h.id.CHECK,this.setting),(e||this.setting.check.chkStyle===h.radio.STYLE)&&f.checkNodeRelation(this.setting,b),f.setChkClass(this.setting,a,b),f.repairParentChkClassWithSelf(this.setting,b),d&&this.setting.treeObj.trigger(h.event.CHECK,[null,this.setting.treeId,b])};d.checkAllNodes=function(b){f.repairAllChk(this.setting,!!b)};d.getCheckedNodes=function(b){var a=this.setting.data.key.children;
return g.getTreeCheckedNodes(this.setting,g.getRoot(this.setting)[a],b!==!1)};d.getChangeCheckedNodes=function(){var b=this.setting.data.key.children;return g.getTreeChangeCheckedNodes(this.setting,g.getRoot(this.setting)[b])};d.setChkDisabled=function(b,a,e,d){a=!!a;e=!!e;f.repairSonChkDisabled(this.setting,b,a,!!d);f.repairParentChkDisabled(this.setting,b.getParentNode(),a,e)};var a=d.updateNode;d.updateNode=function(b,c){a&&a.apply(d,arguments);if(b&&this.setting.check.enable&&n(b,this.setting).get(0)&&
l.uCanDo(this.setting)){var e=n(b,h.id.CHECK,this.setting);(c==!0||this.setting.check.chkStyle===h.radio.STYLE)&&f.checkNodeRelation(this.setting,b);f.setChkClass(this.setting,e,b);f.repairParentChkClassWithSelf(this.setting,b)}}});var k=f.createNodes;f.createNodes=function(g,d,a,b){k&&k.apply(f,arguments);a&&f.repairParentChkClassWithSelf(g,b)};var j=f.removeNode;f.removeNode=function(g,d){var a=d.getParentNode();j&&j.apply(f,arguments);d&&a&&(f.repairChkClass(g,a),f.repairParentChkClass(g,a))};
var u=f.appendNodes;f.appendNodes=function(h,d,a,b){var c="";u&&(c=u.apply(f,arguments));b&&g.makeChkFlag(h,b);return c}})(jQuery);
(function(p){var s={event:{DRAG:"ztree_drag",DROP:"ztree_drop",RENAME:"ztree_rename",DRAGMOVE:"ztree_dragmove"},id:{EDIT:"_edit",INPUT:"_input",REMOVE:"_remove"},move:{TYPE_INNER:"inner",TYPE_PREV:"prev",TYPE_NEXT:"next"},node:{CURSELECTED_EDIT:"curSelectedNode_Edit",TMPTARGET_TREE:"tmpTargetzTree",TMPTARGET_NODE:"tmpTargetNode"}},t={onHoverOverNode:function(b,a){var e=g.getSetting(b.data.treeId),d=g.getRoot(e);if(d.curHoverNode!=a)t.onHoverOutNode(b);d.curHoverNode=a;f.addHoverDom(e,a)},onHoverOutNode:function(b){var b=
g.getSetting(b.data.treeId),a=g.getRoot(b);if(a.curHoverNode&&!g.isSelectedNode(b,a.curHoverNode))f.removeTreeDom(b,a.curHoverNode),a.curHoverNode=null},onMousedownNode:function(b,a){function e(b){if(D.dragFlag==0&&Math.abs(S-b.clientX)<k.edit.drag.minMoveSize&&Math.abs(T-b.clientY)<k.edit.drag.minMoveSize)return!0;var a,c,e,m,i;i=k.data.key.children;K.css("cursor","pointer");if(D.dragFlag==0){if(l.apply(k.callback.beforeDrag,[k.treeId,v],!0)==!1)return d(b),!0;a=0;for(c=v.length;a<c;a++){if(a==0)D.dragNodeShowBefore=
[];e=v[a];e.isParent&&e.open?(f.expandCollapseNode(k,e,!e.open),D.dragNodeShowBefore[e.tId]=!0):D.dragNodeShowBefore[e.tId]=!1}D.dragFlag=1;u.showHoverDom=!1;l.showIfameMask(k,!0);e=!0;m=-1;if(v.length>1){var j=v[0].parentTId?v[0].getParentNode()[i]:g.getNodes(k);i=[];a=0;for(c=j.length;a<c;a++)if(D.dragNodeShowBefore[j[a].tId]!==void 0&&(e&&m>-1&&m+1!==a&&(e=!1),i.push(j[a]),m=a),v.length===i.length){v=i;break}}e&&(M=v[0].getPreNode(),N=v[v.length-1].getNextNode());E=n("<ul class='zTreeDragUL'></ul>",
k);a=0;for(c=v.length;a<c;a++)e=v[a],e.editNameFlag=!1,f.selectNode(k,e,a>0),f.removeTreeDom(k,e),a>k.edit.drag.maxShowNodeNum-1||(m=n("<li id='"+e.tId+"_tmp'></li>",k),m.append(n(e,h.id.A,k).clone()),m.css("padding","0"),m.children("#"+e.tId+h.id.A).removeClass(h.node.CURSELECTED),E.append(m),a==k.edit.drag.maxShowNodeNum-1&&(m=n("<li id='"+e.tId+"_moretmp'><a>  ...  </a></li>",k),E.append(m)));E.attr("id",v[0].tId+h.id.UL+"_tmp");E.addClass(k.treeObj.attr("class"));E.appendTo(K);C=n("<span class='tmpzTreeMove_arrow'></span>",
k);C.attr("id","zTreeMove_arrow_tmp");C.appendTo(K);k.treeObj.trigger(h.event.DRAG,[b,k.treeId,v])}if(D.dragFlag==1){x&&C.attr("id")==b.target.id&&y&&b.clientX+H.scrollLeft()+2>p("#"+y+h.id.A,x).offset().left?(e=p("#"+y+h.id.A,x),b.target=e.length>0?e.get(0):b.target):x&&(x.removeClass(h.node.TMPTARGET_TREE),y&&p("#"+y+h.id.A,x).removeClass(h.node.TMPTARGET_NODE+"_"+h.move.TYPE_PREV).removeClass(h.node.TMPTARGET_NODE+"_"+s.move.TYPE_NEXT).removeClass(h.node.TMPTARGET_NODE+"_"+s.move.TYPE_INNER));
y=x=null;J=!1;r=k;e=g.getSettings();for(var w in e)if(e[w].treeId&&e[w].edit.enable&&e[w].treeId!=k.treeId&&(b.target.id==e[w].treeId||p(b.target).parents("#"+e[w].treeId).length>0))J=!0,r=e[w];w=H.scrollTop();m=H.scrollLeft();i=r.treeObj.offset();a=r.treeObj.get(0).scrollHeight;e=r.treeObj.get(0).scrollWidth;c=b.clientY+w-i.top;var A=r.treeObj.height()+i.top-b.clientY-w,q=b.clientX+m-i.left,t=r.treeObj.width()+i.left-b.clientX-m;i=c<k.edit.drag.borderMax&&c>k.edit.drag.borderMin;var j=A<k.edit.drag.borderMax&&
A>k.edit.drag.borderMin,I=q<k.edit.drag.borderMax&&q>k.edit.drag.borderMin,G=t<k.edit.drag.borderMax&&t>k.edit.drag.borderMin,A=c>k.edit.drag.borderMin&&A>k.edit.drag.borderMin&&q>k.edit.drag.borderMin&&t>k.edit.drag.borderMin,q=i&&r.treeObj.scrollTop()<=0,t=j&&r.treeObj.scrollTop()+r.treeObj.height()+10>=a,L=I&&r.treeObj.scrollLeft()<=0,U=G&&r.treeObj.scrollLeft()+r.treeObj.width()+10>=e;if(b.target&&l.isChildOrSelf(b.target,r.treeId)){for(var F=b.target;F&&F.tagName&&!l.eqs(F.tagName,"li")&&F.id!=
r.treeId;)F=F.parentNode;var O=!0;a=0;for(c=v.length;a<c;a++)if(e=v[a],F.id===e.tId){O=!1;break}else if(n(e,k).find("#"+F.id).length>0){O=!1;break}if(O&&b.target&&l.isChildOrSelf(b.target,F.id+h.id.A))x=p(F),y=F.id}e=v[0];if(A&&l.isChildOrSelf(b.target,r.treeId)){if(!x&&(b.target.id==r.treeId||q||t||L||U)&&(J||!J&&e.parentTId))x=r.treeObj;i?r.treeObj.scrollTop(r.treeObj.scrollTop()-10):j&&r.treeObj.scrollTop(r.treeObj.scrollTop()+10);I?r.treeObj.scrollLeft(r.treeObj.scrollLeft()-10):G&&r.treeObj.scrollLeft(r.treeObj.scrollLeft()+
10);x&&x!=r.treeObj&&x.offset().left<r.treeObj.offset().left&&r.treeObj.scrollLeft(r.treeObj.scrollLeft()+x.offset().left-r.treeObj.offset().left)}E.css({top:b.clientY+w+3+"px",left:b.clientX+m+3+"px"});i=a=0;if(x&&x.attr("id")!=r.treeId){var B=y==null?null:g.getNodeCache(r,y);c=(b.ctrlKey||b.metaKey)&&k.edit.drag.isMove&&k.edit.drag.isCopy||!k.edit.drag.isMove&&k.edit.drag.isCopy;a=!!(M&&y===M.tId);i=!!(N&&y===N.tId);m=e.parentTId&&e.parentTId==y;e=(c||!i)&&l.apply(r.edit.drag.prev,[r.treeId,v,B],
!!r.edit.drag.prev);a=(c||!a)&&l.apply(r.edit.drag.next,[r.treeId,v,B],!!r.edit.drag.next);G=(c||!m)&&!(r.data.keep.leaf&&!B.isParent)&&l.apply(r.edit.drag.inner,[r.treeId,v,B],!!r.edit.drag.inner);if(!e&&!a&&!G){if(x=null,y="",z=h.move.TYPE_INNER,C.css({display:"none"}),window.zTreeMoveTimer)clearTimeout(window.zTreeMoveTimer),window.zTreeMoveTargetNodeTId=null}else{c=p("#"+y+h.id.A,x);i=B.isLastNode?null:p("#"+B.getNextNode().tId+h.id.A,x.next());j=c.offset().top;m=c.offset().left;I=e?G?0.25:a?
0.5:1:-1;G=a?G?0.75:e?0.5:0:-1;w=(b.clientY+w-j)/c.height();(I==1||w<=I&&w>=-0.2)&&e?(a=1-C.width(),i=j-C.height()/2,z=h.move.TYPE_PREV):(G==0||w>=G&&w<=1.2)&&a?(a=1-C.width(),i=i==null||B.isParent&&B.open?j+c.height()-C.height()/2:i.offset().top-C.height()/2,z=h.move.TYPE_NEXT):(a=5-C.width(),i=j,z=h.move.TYPE_INNER);C.css({display:"block",top:i+"px",left:m+a+"px"});c.addClass(h.node.TMPTARGET_NODE+"_"+z);if(P!=y||Q!=z)R=(new Date).getTime();if(B&&B.isParent&&z==h.move.TYPE_INNER&&(w=!0,window.zTreeMoveTimer&&
window.zTreeMoveTargetNodeTId!==B.tId?(clearTimeout(window.zTreeMoveTimer),window.zTreeMoveTargetNodeTId=null):window.zTreeMoveTimer&&window.zTreeMoveTargetNodeTId===B.tId&&(w=!1),w))window.zTreeMoveTimer=setTimeout(function(){z==h.move.TYPE_INNER&&B&&B.isParent&&!B.open&&(new Date).getTime()-R>r.edit.drag.autoOpenTime&&l.apply(r.callback.beforeDragOpen,[r.treeId,B],!0)&&(f.switchNode(r,B),r.edit.drag.autoExpandTrigger&&r.treeObj.trigger(h.event.EXPAND,[r.treeId,B]))},r.edit.drag.autoOpenTime+50),
window.zTreeMoveTargetNodeTId=B.tId}}else if(z=h.move.TYPE_INNER,x&&l.apply(r.edit.drag.inner,[r.treeId,v,null],!!r.edit.drag.inner)?x.addClass(h.node.TMPTARGET_TREE):x=null,C.css({display:"none"}),window.zTreeMoveTimer)clearTimeout(window.zTreeMoveTimer),window.zTreeMoveTargetNodeTId=null;P=y;Q=z;k.treeObj.trigger(h.event.DRAGMOVE,[b,k.treeId,v])}return!1}function d(b){if(window.zTreeMoveTimer)clearTimeout(window.zTreeMoveTimer),window.zTreeMoveTargetNodeTId=null;Q=P=null;H.unbind("mousemove",e);
H.unbind("mouseup",d);H.unbind("selectstart",m);K.css("cursor","auto");x&&(x.removeClass(h.node.TMPTARGET_TREE),y&&p("#"+y+h.id.A,x).removeClass(h.node.TMPTARGET_NODE+"_"+h.move.TYPE_PREV).removeClass(h.node.TMPTARGET_NODE+"_"+s.move.TYPE_NEXT).removeClass(h.node.TMPTARGET_NODE+"_"+s.move.TYPE_INNER));l.showIfameMask(k,!1);u.showHoverDom=!0;if(D.dragFlag!=0){D.dragFlag=0;var a,c,i;a=0;for(c=v.length;a<c;a++)i=v[a],i.isParent&&D.dragNodeShowBefore[i.tId]&&!i.open&&(f.expandCollapseNode(k,i,!i.open),
delete D.dragNodeShowBefore[i.tId]);E&&E.remove();C&&C.remove();var j=(b.ctrlKey||b.metaKey)&&k.edit.drag.isMove&&k.edit.drag.isCopy||!k.edit.drag.isMove&&k.edit.drag.isCopy;!j&&x&&y&&v[0].parentTId&&y==v[0].parentTId&&z==h.move.TYPE_INNER&&(x=null);if(x){var w=y==null?null:g.getNodeCache(r,y);if(l.apply(k.callback.beforeDrop,[r.treeId,v,w,z,j],!0)==!1)f.selectNodes(L,v);else{var A=j?l.clone(v):v;a=function(){if(J){if(!j)for(var a=0,c=v.length;a<c;a++)f.removeNode(k,v[a]);if(z==h.move.TYPE_INNER)f.addNodes(r,
w,A);else if(f.addNodes(r,w.getParentNode(),A),z==h.move.TYPE_PREV){a=0;for(c=A.length;a<c;a++)f.moveNode(r,w,A[a],z,!1)}else{a=-1;for(c=A.length-1;a<c;c--)f.moveNode(r,w,A[c],z,!1)}}else if(j&&z==h.move.TYPE_INNER)f.addNodes(r,w,A);else if(j&&f.addNodes(r,w.getParentNode(),A),z!=h.move.TYPE_NEXT){a=0;for(c=A.length;a<c;a++)f.moveNode(r,w,A[a],z,!1)}else{a=-1;for(c=A.length-1;a<c;c--)f.moveNode(r,w,A[c],z,!1)}f.selectNodes(r,A);n(A[0],k).focus().blur();k.treeObj.trigger(h.event.DROP,[b,r.treeId,A,
w,z,j])};z==h.move.TYPE_INNER&&l.canAsync(r,w)?f.asyncNode(r,w,!1,a):a()}}else f.selectNodes(L,v),k.treeObj.trigger(h.event.DROP,[b,k.treeId,v,null,null,null])}}function m(){return!1}var i,j,k=g.getSetting(b.data.treeId),D=g.getRoot(k),u=g.getRoots();if(b.button==2||!k.edit.enable||!k.edit.drag.isCopy&&!k.edit.drag.isMove)return!0;var q=b.target,t=g.getRoot(k).curSelectedList,v=[];if(g.isSelectedNode(k,a)){i=0;for(j=t.length;i<j;i++){if(t[i].editNameFlag&&l.eqs(q.tagName,"input")&&q.getAttribute("treeNode"+
h.id.INPUT)!==null)return!0;v.push(t[i]);if(v[0].parentTId!==t[i].parentTId){v=[a];break}}}else v=[a];f.editNodeBlur=!0;f.cancelCurEditNode(k);var H=p(k.treeObj.get(0).ownerDocument),K=p(k.treeObj.get(0).ownerDocument.body),E,C,x,J=!1,r=k,L=k,M,N,P=null,Q=null,y=null,z=h.move.TYPE_INNER,S=b.clientX,T=b.clientY,R=(new Date).getTime();l.uCanDo(k)&&H.bind("mousemove",e);H.bind("mouseup",d);H.bind("selectstart",m);b.preventDefault&&b.preventDefault();return!0}};p.extend(!0,p.fn.zTree.consts,s);p.extend(!0,
p.fn.zTree._z,{tools:{getAbs:function(b){b=b.getBoundingClientRect();return[b.left+(document.body.scrollLeft+document.documentElement.scrollLeft),b.top+(document.body.scrollTop+document.documentElement.scrollTop)]},inputFocus:function(b){b.get(0)&&(b.focus(),l.setCursorPosition(b.get(0),b.val().length))},inputSelect:function(b){b.get(0)&&(b.focus(),b.select())},setCursorPosition:function(b,a){if(b.setSelectionRange)b.focus(),b.setSelectionRange(a,a);else if(b.createTextRange){var e=b.createTextRange();
e.collapse(!0);e.moveEnd("character",a);e.moveStart("character",a);e.select()}},showIfameMask:function(b,a){for(var e=g.getRoot(b);e.dragMaskList.length>0;)e.dragMaskList[0].remove(),e.dragMaskList.shift();if(a)for(var d=n("iframe",b),f=0,h=d.length;f<h;f++){var k=d.get(f),i=l.getAbs(k),k=n("<div id='zTreeMask_"+f+"' class='zTreeMask' style='top:"+i[1]+"px; left:"+i[0]+"px; width:"+k.offsetWidth+"px; height:"+k.offsetHeight+"px;'></div>",b);k.appendTo(n("body",b));e.dragMaskList.push(k)}}},view:{addEditBtn:function(b,
a){if(!(a.editNameFlag||n(a,h.id.EDIT,b).length>0)&&l.apply(b.edit.showRenameBtn,[b.treeId,a],b.edit.showRenameBtn)){var e=n(a,h.id.A,b),d="<span class='"+h.className.BUTTON+" edit' id='"+a.tId+h.id.EDIT+"' title='"+l.apply(b.edit.renameTitle,[b.treeId,a],b.edit.renameTitle)+"' treeNode"+h.id.EDIT+" style='display:none;'></span>";e.append(d);n(a,h.id.EDIT,b).bind("click",function(){if(!l.uCanDo(b)||l.apply(b.callback.beforeEditName,[b.treeId,a],!0)==!1)return!1;f.editNode(b,a);return!1}).show()}},
addRemoveBtn:function(b,a){if(!(a.editNameFlag||n(a,h.id.REMOVE,b).length>0)&&l.apply(b.edit.showRemoveBtn,[b.treeId,a],b.edit.showRemoveBtn)){var e=n(a,h.id.A,b),d="<span class='"+h.className.BUTTON+" remove' id='"+a.tId+h.id.REMOVE+"' title='"+l.apply(b.edit.removeTitle,[b.treeId,a],b.edit.removeTitle)+"' treeNode"+h.id.REMOVE+" style='display:none;'></span>";e.append(d);n(a,h.id.REMOVE,b).bind("click",function(){if(!l.uCanDo(b)||l.apply(b.callback.beforeRemove,[b.treeId,a],!0)==!1)return!1;f.removeNode(b,
a);b.treeObj.trigger(h.event.REMOVE,[b.treeId,a]);return!1}).bind("mousedown",function(){return!0}).show()}},addHoverDom:function(b,a){if(g.getRoots().showHoverDom)a.isHover=!0,b.edit.enable&&(f.addEditBtn(b,a),f.addRemoveBtn(b,a)),l.apply(b.view.addHoverDom,[b.treeId,a])},cancelCurEditNode:function(b,a,e){var d=g.getRoot(b),m=b.data.key.name,k=d.curEditNode;if(k){var i=d.curEditInput,a=a?a:e?k[m]:i.val();if(l.apply(b.callback.beforeRename,[b.treeId,k,a,e],!0)===!1)return!1;k[m]=a;n(k,h.id.A,b).removeClass(h.node.CURSELECTED_EDIT);
i.unbind();f.setNodeName(b,k);k.editNameFlag=!1;d.curEditNode=null;d.curEditInput=null;f.selectNode(b,k,!1);b.treeObj.trigger(h.event.RENAME,[b.treeId,k,e])}return d.noSelection=!0},editNode:function(b,a){var e=g.getRoot(b);f.editNodeBlur=!1;if(g.isSelectedNode(b,a)&&e.curEditNode==a&&a.editNameFlag)setTimeout(function(){l.inputFocus(e.curEditInput)},0);else{var d=b.data.key.name;a.editNameFlag=!0;f.removeTreeDom(b,a);f.cancelCurEditNode(b);f.selectNode(b,a,!1);n(a,h.id.SPAN,b).html("<input type=text class='rename' id='"+
a.tId+h.id.INPUT+"' treeNode"+h.id.INPUT+" >");var m=n(a,h.id.INPUT,b);m.attr("value",a[d]);b.edit.editNameSelectAll?l.inputSelect(m):l.inputFocus(m);m.bind("blur",function(){f.editNodeBlur||f.cancelCurEditNode(b)}).bind("keydown",function(a){a.keyCode=="13"?(f.editNodeBlur=!0,f.cancelCurEditNode(b)):a.keyCode=="27"&&f.cancelCurEditNode(b,null,!0)}).bind("click",function(){return!1}).bind("dblclick",function(){return!1});n(a,h.id.A,b).addClass(h.node.CURSELECTED_EDIT);e.curEditInput=m;e.noSelection=
!1;e.curEditNode=a}},moveNode:function(b,a,e,d,m,k){var i=g.getRoot(b),j=b.data.key.children;if(a!=e&&(!b.data.keep.leaf||!a||a.isParent||d!=h.move.TYPE_INNER)){var l=e.parentTId?e.getParentNode():i,p=a===null||a==i;p&&a===null&&(a=i);if(p)d=h.move.TYPE_INNER;i=a.parentTId?a.getParentNode():i;if(d!=h.move.TYPE_PREV&&d!=h.move.TYPE_NEXT)d=h.move.TYPE_INNER;if(d==h.move.TYPE_INNER)if(p)e.parentTId=null;else{if(!a.isParent)a.isParent=!0,a.open=!!a.open,f.setNodeLineIcos(b,a);e.parentTId=a.tId}var u;
p?u=p=b.treeObj:(!k&&d==h.move.TYPE_INNER?f.expandCollapseNode(b,a,!0,!1):k||f.expandCollapseNode(b,a.getParentNode(),!0,!1),p=n(a,b),u=n(a,h.id.UL,b),p.get(0)&&!u.get(0)&&(u=[],f.makeUlHtml(b,a,u,""),p.append(u.join(""))),u=n(a,h.id.UL,b));var q=n(e,b);q.get(0)?p.get(0)||q.remove():q=f.appendNodes(b,e.level,[e],null,!1,!0).join("");u.get(0)&&d==h.move.TYPE_INNER?u.append(q):p.get(0)&&d==h.move.TYPE_PREV?p.before(q):p.get(0)&&d==h.move.TYPE_NEXT&&p.after(q);var v=-1,s=0,t=null,p=null,E=e.level;if(e.isFirstNode){if(v=
0,l[j].length>1)t=l[j][1],t.isFirstNode=!0}else if(e.isLastNode)v=l[j].length-1,t=l[j][v-1],t.isLastNode=!0;else{u=0;for(q=l[j].length;u<q;u++)if(l[j][u].tId==e.tId){v=u;break}}v>=0&&l[j].splice(v,1);if(d!=h.move.TYPE_INNER){u=0;for(q=i[j].length;u<q;u++)i[j][u].tId==a.tId&&(s=u)}if(d==h.move.TYPE_INNER){a[j]||(a[j]=[]);if(a[j].length>0)p=a[j][a[j].length-1],p.isLastNode=!1;a[j].splice(a[j].length,0,e);e.isLastNode=!0;e.isFirstNode=a[j].length==1}else a.isFirstNode&&d==h.move.TYPE_PREV?(i[j].splice(s,
0,e),p=a,p.isFirstNode=!1,e.parentTId=a.parentTId,e.isFirstNode=!0,e.isLastNode=!1):a.isLastNode&&d==h.move.TYPE_NEXT?(i[j].splice(s+1,0,e),p=a,p.isLastNode=!1,e.parentTId=a.parentTId,e.isFirstNode=!1,e.isLastNode=!0):(d==h.move.TYPE_PREV?i[j].splice(s,0,e):i[j].splice(s+1,0,e),e.parentTId=a.parentTId,e.isFirstNode=!1,e.isLastNode=!1);g.fixPIdKeyValue(b,e);g.setSonNodeLevel(b,e.getParentNode(),e);f.setNodeLineIcos(b,e);f.repairNodeLevelClass(b,e,E);!b.data.keep.parent&&l[j].length<1?(l.isParent=!1,
l.open=!1,a=n(l,h.id.UL,b),d=n(l,h.id.SWITCH,b),j=n(l,h.id.ICON,b),f.replaceSwitchClass(l,d,h.folder.DOCU),f.replaceIcoClass(l,j,h.folder.DOCU),a.css("display","none")):t&&f.setNodeLineIcos(b,t);p&&f.setNodeLineIcos(b,p);b.check&&b.check.enable&&f.repairChkClass&&(f.repairChkClass(b,l),f.repairParentChkClassWithSelf(b,l),l!=e.parent&&f.repairParentChkClassWithSelf(b,e));k||f.expandCollapseParentNode(b,e.getParentNode(),!0,m)}},removeEditBtn:function(b,a){n(a,h.id.EDIT,b).unbind().remove()},removeRemoveBtn:function(b,
a){n(a,h.id.REMOVE,b).unbind().remove()},removeTreeDom:function(b,a){a.isHover=!1;f.removeEditBtn(b,a);f.removeRemoveBtn(b,a);l.apply(b.view.removeHoverDom,[b.treeId,a])},repairNodeLevelClass:function(b,a,e){if(e!==a.level){var d=n(a,b),g=n(a,h.id.A,b),b=n(a,h.id.UL,b),e=h.className.LEVEL+e,a=h.className.LEVEL+a.level;d.removeClass(e);d.addClass(a);g.removeClass(e);g.addClass(a);b.removeClass(e);b.addClass(a)}},selectNodes:function(b,a){for(var e=0,d=a.length;e<d;e++)f.selectNode(b,a[e],e>0)}},event:{},
data:{setSonNodeLevel:function(b,a,e){if(e){var d=b.data.key.children;e.level=a?a.level+1:0;if(e[d])for(var a=0,f=e[d].length;a<f;a++)e[d][a]&&g.setSonNodeLevel(b,e,e[d][a])}}}});var q=p.fn.zTree,l=q._z.tools,h=q.consts,f=q._z.view,g=q._z.data,n=l.$;g.exSetting({edit:{enable:!1,editNameSelectAll:!1,showRemoveBtn:!0,showRenameBtn:!0,removeTitle:"remove",renameTitle:"rename",drag:{autoExpandTrigger:!1,isCopy:!0,isMove:!0,prev:!0,next:!0,inner:!0,minMoveSize:5,borderMax:10,borderMin:-5,maxShowNodeNum:5,
autoOpenTime:500}},view:{addHoverDom:null,removeHoverDom:null},callback:{beforeDrag:null,beforeDragOpen:null,beforeDrop:null,beforeEditName:null,beforeRename:null,onDrag:null,onDragMove:null,onDrop:null,onRename:null}});g.addInitBind(function(b){var a=b.treeObj,e=h.event;a.bind(e.RENAME,function(a,e,c,d){l.apply(b.callback.onRename,[a,e,c,d])});a.bind(e.DRAG,function(a,e,c,d){l.apply(b.callback.onDrag,[e,c,d])});a.bind(e.DRAGMOVE,function(a,e,c,d){l.apply(b.callback.onDragMove,[e,c,d])});a.bind(e.DROP,
function(a,e,c,d,g,f,h){l.apply(b.callback.onDrop,[e,c,d,g,f,h])})});g.addInitUnBind(function(b){var b=b.treeObj,a=h.event;b.unbind(a.RENAME);b.unbind(a.DRAG);b.unbind(a.DRAGMOVE);b.unbind(a.DROP)});g.addInitCache(function(){});g.addInitNode(function(a,c,e){if(e)e.isHover=!1,e.editNameFlag=!1});g.addInitProxy(function(a){var c=a.target,e=g.getSetting(a.data.treeId),d=a.relatedTarget,f="",k=null,i="",j=null,n=null;if(l.eqs(a.type,"mouseover")){if(n=l.getMDom(e,c,[{tagName:"a",attrName:"treeNode"+h.id.A}]))f=
l.getNodeMainDom(n).id,i="hoverOverNode"}else if(l.eqs(a.type,"mouseout"))n=l.getMDom(e,d,[{tagName:"a",attrName:"treeNode"+h.id.A}]),n||(f="remove",i="hoverOutNode");else if(l.eqs(a.type,"mousedown")&&(n=l.getMDom(e,c,[{tagName:"a",attrName:"treeNode"+h.id.A}])))f=l.getNodeMainDom(n).id,i="mousedownNode";if(f.length>0)switch(k=g.getNodeCache(e,f),i){case "mousedownNode":j=t.onMousedownNode;break;case "hoverOverNode":j=t.onHoverOverNode;break;case "hoverOutNode":j=t.onHoverOutNode}return{stop:!1,
node:k,nodeEventType:i,nodeEventCallback:j,treeEventType:"",treeEventCallback:null}});g.addInitRoot(function(a){var a=g.getRoot(a),c=g.getRoots();a.curEditNode=null;a.curEditInput=null;a.curHoverNode=null;a.dragFlag=0;a.dragNodeShowBefore=[];a.dragMaskList=[];c.showHoverDom=!0});g.addZTreeTools(function(a,c){c.cancelEditName=function(a){g.getRoot(this.setting).curEditNode&&f.cancelCurEditNode(this.setting,a?a:null,!0)};c.copyNode=function(a,b,c,d){if(!b)return null;if(a&&!a.isParent&&this.setting.data.keep.leaf&&
c===h.move.TYPE_INNER)return null;var g=this,k=l.clone(b);if(!a)a=null,c=h.move.TYPE_INNER;c==h.move.TYPE_INNER?(b=function(){f.addNodes(g.setting,a,[k],d)},l.canAsync(this.setting,a)?f.asyncNode(this.setting,a,d,b):b()):(f.addNodes(this.setting,a.parentNode,[k],d),f.moveNode(this.setting,a,k,c,!1,d));return k};c.editName=function(a){a&&a.tId&&a===g.getNodeCache(this.setting,a.tId)&&(a.parentTId&&f.expandCollapseParentNode(this.setting,a.getParentNode(),!0),f.editNode(this.setting,a))};c.moveNode=
function(a,b,c,d){function g(){f.moveNode(k.setting,a,b,c,!1,d)}if(!b)return b;if(a&&!a.isParent&&this.setting.data.keep.leaf&&c===h.move.TYPE_INNER)return null;else if(a&&(b.parentTId==a.tId&&c==h.move.TYPE_INNER||n(b,this.setting).find("#"+a.tId).length>0))return null;else a||(a=null);var k=this;l.canAsync(this.setting,a)&&c===h.move.TYPE_INNER?f.asyncNode(this.setting,a,d,g):g();return b};c.setEditable=function(a){this.setting.edit.enable=a;return this.refresh()}});var k=f.cancelPreSelectedNode;
f.cancelPreSelectedNode=function(a,c){for(var e=g.getRoot(a).curSelectedList,d=0,h=e.length;d<h;d++)if(!c||c===e[d])if(f.removeTreeDom(a,e[d]),c)break;k&&k.apply(f,arguments)};var j=f.createNodes;f.createNodes=function(a,c,e,d){j&&j.apply(f,arguments);e&&f.repairParentChkClassWithSelf&&f.repairParentChkClassWithSelf(a,d)};var u=f.makeNodeUrl;f.makeNodeUrl=function(a){return a.edit.enable?null:u.apply(f,arguments)};var i=f.removeNode;f.removeNode=function(a,c){var e=g.getRoot(a);if(e.curEditNode===
c)e.curEditNode=null;i&&i.apply(f,arguments)};var d=f.selectNode;f.selectNode=function(a,c){var e=g.getRoot(a);if(g.isSelectedNode(a,c)&&e.curEditNode==c&&c.editNameFlag)return!1;d&&d.apply(f,arguments);f.addHoverDom(a,c);return!0};var a=l.uCanDo;l.uCanDo=function(b,c){var e=g.getRoot(b);if(c&&(l.eqs(c.type,"mouseover")||l.eqs(c.type,"mouseout")||l.eqs(c.type,"mousedown")||l.eqs(c.type,"mouseup")))return!0;if(e.curEditNode)f.editNodeBlur=!1,e.curEditInput.focus();return!e.curEditNode&&(a?a.apply(f,
arguments):!0)}})(jQuery);
(function(p){p.extend(!0,p.fn.zTree._z,{view:{clearOldFirstNode:function(d,a){for(var b=a.getNextNode();b;){if(b.isFirstNode){b.isFirstNode=!1;l.setNodeLineIcos(d,b);break}if(b.isLastNode)break;b=b.getNextNode()}},clearOldLastNode:function(d,a){for(var b=a.getPreNode();b;){if(b.isLastNode){b.isLastNode=!1;l.setNodeLineIcos(d,b);break}if(b.isFirstNode)break;b=b.getPreNode()}},makeDOMNodeMainBefore:function(d,a,b){d.push("<li ",b.isHidden?"style='display:none;' ":"","id='",b.tId,"' class='level",b.level,
"' tabindex='0' hidefocus='true' treenode>")},showNode:function(d,a){a.isHidden=!1;h.initShowForExCheck(d,a);p("#"+a.tId).show()},showNodes:function(d,a,b){if(a&&a.length!=0){var c={},e,g;e=0;for(g=a.length;e<g;e++){var f=a[e];if(!c[f.parentTId]){var k=f.getParentNode();c[f.parentTId]=k===null?h.getRoot(d):f.getParentNode()}l.showNode(d,f,b)}for(var i in c)a=c[i][d.data.key.children],l.setFirstNodeForShow(d,a),l.setLastNodeForShow(d,a)}},hideNode:function(d,a){a.isHidden=!0;a.isFirstNode=!1;a.isLastNode=
!1;h.initHideForExCheck(d,a);l.cancelPreSelectedNode(d,a);p("#"+a.tId).hide()},hideNodes:function(d,a,b){if(a&&a.length!=0){var c={},e,g;e=0;for(g=a.length;e<g;e++){var f=a[e];if((f.isFirstNode||f.isLastNode)&&!c[f.parentTId]){var k=f.getParentNode();c[f.parentTId]=k===null?h.getRoot(d):f.getParentNode()}l.hideNode(d,f,b)}for(var i in c)a=c[i][d.data.key.children],l.setFirstNodeForHide(d,a),l.setLastNodeForHide(d,a)}},setFirstNode:function(d,a){var b=d.data.key.children,c=a[b].length;c>0&&!a[b][0].isHidden?
a[b][0].isFirstNode=!0:c>0&&l.setFirstNodeForHide(d,a[b])},setLastNode:function(d,a){var b=d.data.key.children,c=a[b].length;c>0&&!a[b][0].isHidden?a[b][c-1].isLastNode=!0:c>0&&l.setLastNodeForHide(d,a[b])},setFirstNodeForHide:function(d,a){var b,c,e;c=0;for(e=a.length;c<e;c++){b=a[c];if(b.isFirstNode)break;if(!b.isHidden&&!b.isFirstNode){b.isFirstNode=!0;l.setNodeLineIcos(d,b);break}else b=null}return b},setFirstNodeForShow:function(d,a){var b,c,e,g,f;c=0;for(e=a.length;c<e;c++)if(b=a[c],!g&&!b.isHidden&&
b.isFirstNode){g=b;break}else if(!g&&!b.isHidden&&!b.isFirstNode)b.isFirstNode=!0,g=b,l.setNodeLineIcos(d,b);else if(g&&b.isFirstNode){b.isFirstNode=!1;f=b;l.setNodeLineIcos(d,b);break}return{"new":g,old:f}},setLastNodeForHide:function(d,a){var b,c;for(c=a.length-1;c>=0;c--){b=a[c];if(b.isLastNode)break;if(!b.isHidden&&!b.isLastNode){b.isLastNode=!0;l.setNodeLineIcos(d,b);break}else b=null}return b},setLastNodeForShow:function(d,a){var b,c,e,g;for(c=a.length-1;c>=0;c--)if(b=a[c],!e&&!b.isHidden&&
b.isLastNode){e=b;break}else if(!e&&!b.isHidden&&!b.isLastNode)b.isLastNode=!0,e=b,l.setNodeLineIcos(d,b);else if(e&&b.isLastNode){b.isLastNode=!1;g=b;l.setNodeLineIcos(d,b);break}return{"new":e,old:g}}},data:{initHideForExCheck:function(d,a){if(a.isHidden&&d.check&&d.check.enable)a._nocheck=!!a.nocheck,a.nocheck=!0,a.check_Child_State=-1,l.repairParentChkClassWithSelf&&l.repairParentChkClassWithSelf(d,a)},initShowForExCheck:function(d,a){if(!a.isHidden&&d.check&&d.check.enable){a.nocheck=a._nocheck;
delete a._nocheck;if(l.setChkClass){var b=p("#"+a.tId+q.id.CHECK);l.setChkClass(d,b,a)}l.repairParentChkClassWithSelf&&l.repairParentChkClassWithSelf(d,a)}}}});var s=p.fn.zTree,t=s._z.tools,q=s.consts,l=s._z.view,h=s._z.data;h.addInitNode(function(d,a,b){if(typeof b.isHidden=="string")b.isHidden=t.eqs(b.isHidden,"true");b.isHidden=!!b.isHidden;h.initHideForExCheck(d,b)});h.addBeforeA(function(){});h.addZTreeTools(function(d,a){a.showNodes=function(a,b){l.showNodes(d,a,b)};a.showNode=function(a,b){a&&
l.showNodes(d,[a],b)};a.hideNodes=function(a,b){l.hideNodes(d,a,b)};a.hideNode=function(a,b){a&&l.hideNodes(d,[a],b)};var b=a.checkNode;if(b)a.checkNode=function(c){(!c||!c.isHidden)&&b.apply(a,arguments)}});var f=h.initNode;h.tmpHideParent=-1;h.initNode=function(d,a,b,c,e,g){if(h.tmpHideParent!==c){h.tmpHideParent=c;var k=(c?c:h.getRoot(d))[d.data.key.children];h.tmpHideFirstNode=l.setFirstNodeForHide(d,k);h.tmpHideLastNode=l.setLastNodeForHide(d,k);l.setNodeLineIcos(d,h.tmpHideFirstNode);l.setNodeLineIcos(d,
h.tmpHideLastNode)}g=h.tmpHideLastNode===b;f&&f.apply(h,arguments);g&&l.clearOldLastNode(d,b)};var g=h.makeChkFlag;if(g)h.makeChkFlag=function(d,a){(!a||!a.isHidden)&&g.apply(h,arguments)};var n=h.getTreeCheckedNodes;if(n)h.getTreeCheckedNodes=function(d,a){if(a&&a.length>0){var b=a[0].getParentNode();if(b&&b.isHidden)return[]}return n.apply(h,arguments)};var k=h.getTreeChangeCheckedNodes;if(k)h.getTreeChangeCheckedNodes=function(d,a){if(a&&a.length>0){var b=a[0].getParentNode();if(b&&b.isHidden)return[]}return k.apply(h,
arguments)};var j=l.expandCollapseSonNode;if(j)l.expandCollapseSonNode=function(d,a){(!a||!a.isHidden)&&j.apply(l,arguments)};var u=l.setSonNodeCheckBox;if(u)l.setSonNodeCheckBox=function(d,a){(!a||!a.isHidden)&&u.apply(l,arguments)};var i=l.repairParentChkClassWithSelf;if(i)l.repairParentChkClassWithSelf=function(d,a){(!a||!a.isHidden)&&i.apply(l,arguments)}})(jQuery);
(function(p){if(p.fn.zTree){var s=p.fn.zTree._z.data,t=p.fn.zTree.consts,q=p.fn.zTree._z.view,l=p.fn.zTree._z.tools,h=l.$;s.exSetting({view:{showIcon:!0},data:{simpleData:{enable:!0,pIdKey:"parentId"},key:{name:"label"}},initBigData:!1});s.getTreeCheckedNodes=function(g,f,k,h){if(!f)return[];for(var l=g.data.key.children,i=g.data.key.checked,d=k&&g.check.chkStyle==t.radio.STYLE&&g.check.radioType==t.radio.TYPE_ALL,h=!h?[]:h,a=0,b=f.length;a<b;a++){if(f[a].nocheck!==!0&&(g.check.getCheckedNodesIgnore===
!0||f[a].chkDisabled!==!0)&&f[a][i]==k)if(h.push(f[a]),d)break;s.getTreeCheckedNodes(g,f[a][l],k,h);if(d&&h.length>0)break}return h};s.getNodeCacheId=function(g){return g};s.addInitNode(function(g,f,h){if(h.id)h.tId=g.treeId+"_id_"+h.id;if(h.extra&&h.extra.disablecls&&g.check&&g.check.enable&&g.check.autoDisabledCheck)h.chkDisabled=!0});s.addZTreeTools(function(g,f){f.getNodeById=function(g){return this.getNodeByTId(this.setting.treeId+"_id_"+g)};f.setSonNodeCheckBox=function(g,f,h,i){return q.setSonNodeCheckBox(this.setting,
g,f,h,i)};f.setNodeDisabled=function(g,f){f?p("#"+this.setting.treeId+"_id_"+g+" a").addClass("disabledNode"):p("#"+this.setting.treeId+"_id_"+g+" a").removeClass("disabledNode")};f.setOneGenerationSonNode=function(g,f,h){return q.setOneGenerationSonNode(this.setting,g,f,h)};f.setAllSonNode=function(g,f,h){return q.setAllSonNode(this.setting,g,f,h)}});q.makeNodeIcoClass=function(g,f){var h=["ico"];f.isAjaxing||(h[0]=(f.cls?f.cls+"_":"")+h[0],f.isParent?h.push(f.open?t.folder.OPEN:t.folder.CLOSE):
h.push(t.folder.DOCU));return"button "+h.join("_")};q.makeDOMNodeNameBefore=function(g,f,h){var j=s.getNodeTitle(f,h),p=q.makeNodeUrl(f,h),i=q.makeNodeFontCss(f,h),d=[],a;for(a in i)i.hasOwnProperty(a)&&d.push(a,":",i[a],";");a=i="";if(h.extra){if(h.extra.disablecls)i=h.extra.disablecls;if(h.extra.selectedcls)a=h.extra.selectedcls,s.addSelectedNode(f,h)}h.chkDisabled&&(i=h.chkDisabled?"disabledNode":"");g.push("<a id='",h.tId,t.id.A,"' "+(i=="disabledNode"?"disabled='disabled'":"")+" class='level",
h.level," ",i," ",a,"' treeNode",t.id.A,' onclick="',h.click||"",'" ',p!=null&&p.length>0?"href='"+p+"'":""," target='",q.makeNodeTarget(h),"' style='",d.join(""),"'");l.apply(f.view.showTitle,[f.treeId,h],f.view.showTitle)&&j&&g.push("title='",j.replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/&/g,"&amp;"),"'");g.push(">")};q.appendNodes=function(g,f,h,j,l,i){if(!h)return[];for(var d=[],a=g.data.key.children,b=0,c=h.length;b<c;b++){var e=h[b];if(l||g.initBigData&&!e._initNodeAttr){var o=
(j?j:s.getRoot(g))[a].length==h.length&&b==0;s.initNode(g,f,e,j,o,b==h.length-1,i);s.addNodeCache(g,e);g.initBigData&&(e._initNodeAttr=!0)}o=[];if(e[a]&&e[a].length>0&&(!g.initBigData||e.open))o=q.appendNodes(g,f+1,e[a],e,l,i&&e.open);i&&(q.makeDOMNodeMainBefore(d,g,e),q.makeDOMNodeLine(d,g,e),s.getBeforeA(g,e,d),q.makeDOMNodeNameBefore(d,g,e),s.getInnerBeforeA(g,e,d),q.makeDOMNodeIcon(d,g,e),s.getInnerAfterA(g,e,d),q.makeDOMNodeNameAfter(d,g,e),q.makeDOMNodeGrid(d,g,e),s.getAfterA(g,e,d),e.isParent&&
e.open&&q.makeUlHtml(g,e,d,o.join("")),q.makeDOMNodeMainAfter(d,g,e),s.addCreatedNode(g,e))}return d};q.makeDOMNodeGrid=function(g,f,h){if(f.view.gridtree){g.push('<div class="extra-row">');if(h.extra.opdata&&h.extra.opdata.length>0)for(f=0;f<h.extra.opdata.length;f++){var j=h.extra.opdata[f];g.push('<span class="col"><span class="check"><label><input id="',j.opCode,h.id,j.opId,'" name="',j.opCode,h.id,'" opCode="',j.opCode,'"','" type="',j.type,'" group-id="',h.id,'" init-check="',j.checked,'"',
j.checked==!0?" checked":"",j.disable==!0?" disabled":"",">",j.opName,"</label></span></span>")}g.push("</div>")}};q.asyncNode=function(g,f,k,j){var u,i;if(f&&!f.isParent)return l.apply(j),!1;else if(f&&f.isAjaxing)return!1;else if(l.apply(g.callback.beforeAsync,[g.treeId,f],!0)==!1)return l.apply(j),!1;if(f)f.isAjaxing=!0,h(f,t.id.ICON,g).attr({style:"","class":t.className.BUTTON+" "+t.className.ICO_LOADING});var d={};u=0;for(i=g.async.autoParam.length;f&&u<i;u++){var a=g.async.autoParam[u].split("="),
b=a;a.length>1&&(b=a[1],a=a[0]);d[b]=f[a]}a=g.async.otherParam;p.isFunction(a)&&(a=a());if(l.isArray(a)){u=0;for(i=a.length;u<i;u+=2)d[a[u]]=a[u+1]}else for(var c in a)d[c]=a[c];var e=s.getRoot(g)._ver;p.ajax({contentType:g.async.contentType,cache:!1,type:g.async.type,url:l.apply(g.async.url,[g.treeId,f],g.async.url),data:d,dataType:g.async.dataType,success:function(a){if(e==s.getRoot(g)._ver){var b=[];try{b=!a||a.length==0?[]:typeof a=="string"?eval("("+a+")"):a}catch(c){b=a}if(f)f.isAjaxing=null,
f.zAsync=!0;q.setNodeLineIcos(g,f);b&&b!==""?(b=l.apply(g.async.dataFilter,[g.treeId,f,b],b),q.addNodes(g,f,b?l.clone(b):[],!!k)):q.addNodes(g,f,[],!!k);g.treeObj.trigger(t.event.ASYNC_SUCCESS,[g.treeId,f,a]);l.apply(j)}},error:function(a,b,c){if(e==s.getRoot(g)._ver){if(f)f.isAjaxing=null;q.setNodeLineIcos(g,f);g.treeObj.trigger(t.event.ASYNC_ERROR,[g.treeId,f,a,b,c])}}});return!0};q.setAllSonNode=function(g,f,h,j){q.checkNodeRelation(g,f);q.setSonNodeCheckBox(g,f,h,j);q.repairParentChkClassWithSelf(g,
f)};q.setOneGenerationSonNode=function(g,f,h,j){if(f){var l=g.data.key.children,i=g.data.key.checked,d=p("#"+f.tId+t.id.CHECK);j||(j=f);if(f[l])for(var a=g.check.chkDisabledCheckedInherit||f.chkDisabled!==!0,b=0,c=f[l].length;b<c&&a;b++){var e=f[l][b],d=p("#"+e.tId+t.id.CHECK);q.checkNodeRelation(g,e);if(e!=s.getRoot(g)&&e.chkDisabled!==!0)e.nocheck!==!0?(e[i]=h,e.check_Child_State=e[l]&&e[l].length>0?h?2:0:-1):e.check_Child_State=-1,q.setChkClass(g,d,e),g.check.autoCheckTrigger&&f!=j&&f.nocheck!==
!0&&g.treeObj.trigger(t.event.CHECK,[g.treeId,e]);q.repairParentChkClassWithSelf(g,e)}}};var f=1;p.fn.tree=function(g,h){if(g==null){var k=this.attr("id");return p.fn.zTree.getZTreeObj(k)}if(g.ajax){var j,l;if(!g.async||!g.async.enable)j=p.fn.zTree.init(this,g,h),l=j.setting.data.key.children;var i=this,d=g.ajax.success,a=g.ajax.error,b,c,e,o,m,q=function(){b=j.setting;c=b.treeObj.zTree._z.data.getRoot(j.setting);e=b.treeObj.zTree._z.tools;o=b.treeObj.zTree._z.data;m=b.treeObj.zTree._z.view},s=function(){i.hide();
i.parent().find(".msg-tips.nodata").remove();i.parent().append('<DIV class="msg-weak msg-tips nodata"><I></I><DIV class=msg-cnt><SPAN>'+language.text("tree.noData")+"</SPAN> </DIV></DIV>")},t=f++;p.extend(g.ajax,{dataType:"json",success:function(a){var f=i.data("treeSeq");f!=null&&f>t||(i.data("treeSeq",t),g.callback&&g.callback.beforeTreeLoad&&g.callback.beforeTreeLoad.call(a)===!1||(a=this.handleData?this.handleData(a):a,a==null||p.isEmptyObject(a)||p.isArray(a)&&a.length===0?(s(),g.callback&&g.callback.dataEmpty&&
g.callback.dataEmpty.call()):(i.show(),g.async&&g.async.enable?g.callback&&g.callback.beforeInitNode&&g.callback.beforeInitNode.call(j,c[l])===!1||(j=p.fn.zTree.init(i,g,a),q(),d&&d.apply(this,arguments),b.callback&&b.callback.initNode&&b.callback.initNode.call(j,c[l])):(q(),a=a?e.clone(e.isArray(a)?a:[a]):[],c[l]=b.data.simpleData.enable?o.transformTozTreeFormat(b,a):a,b.callback.beforeInitNode&&b.callback.beforeInitNode.call(j,c[l])===!1||(m.createNodes(b,0,c[l]),d&&d.apply(this,arguments),b.callback.initNode&&
b.callback.initNode.call(j,c[l]))))))},error:function(){s(language.text("tree.error"));a&&a.apply(this,arguments)}});p.ajax(g.ajax);return j}else return p.fn.zTree.init(this,g,h)};p.fn.searchZtree=function(f){function h(c,f){var g=p(b),i=p.fn.zTree.getZTreeObj(d);g.find("."+a).removeClass(a);if(f!=""&&(g=i.getNodesByParamFuzzy(c,f))&&g.length>0)for(var j,k,l=0;l<g.length;l++){for(k=g[l];(j=i.getNodesByParam("id",k.parentId))&&j[0];)i.expandNode(j[0],!0,!1,!1),k=j[0];p("#"+g[l].tId+"_a").addClass(a)}}
function k(a){p(b);c.init=!0;c.setting=a.setting;c.data=p.fn.zTree._z.tools.clone(a.getNodes())}function j(a,i){var j=p.fn.zTree.getZTreeObj(d),l=j.setting,q=l.async.url,s=l.async.otherParam,t=l.callback=l.callback||{},u=t.onAsyncSuccess;t.onAsyncSuccess=function(){p.isFunction(u)&&u.apply(this,arguments);l.async.url=q;l.async.otherParam=s;t.onAsyncSuccess=u;h(a,i)};if(i==""){if(c.init)c.init=!1,p.fn.zTree.init(p(b),c.setting,c.data)}else c.init||k(j),l.async.url=f.searchUrl||l.ajax.url,l.async.enable=
!0,l.async.type="get",l.async.otherParam=p.extend(!0,p.isArray(s)?["searchVal",i,"searchKey",a]:{searchVal:i,searchKey:a},s),j.reAsyncChildNodes(null,"refresh")}var f=f||{},l=this,i=f.sync!=null?f.sync:!0,d=f.zTreeId.replace(/^#/,""),a=f.cls||"highlight",b="#"+d,c={init:!1};l.bind("searchZtree",function(){var a=p.trim(l.val());if(a!=c.val)c.val=a,i?h(f.key,a):j(f.key,a)});l.bind("keyup",function(a){a.keyCode==13&&p(this).trigger("searchZtree")});f.searchBtn&&p(f.searchBtn).bind("click",function(){l.trigger("searchZtree")})}}})(jQuery);
