define("./ocx_preview",["./active_x"],function(f){var e={},d={};return f("./active_x").extend({ocxNotInstall:!1,params:null,constructor:function(a){this.base(a,["hikui-active"],[])},checkFile:function(a){var b=null;window.XMLHttpRequest?b=new XMLHttpRequest:window.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));if(b!=null){if(b.open("HEAD",a,!1),b.send(),b.readyState==4&&b.status==404)return!1}else jAlert(language.text("ocx.supportXmlHTTP"));return!0},render:function(){if($.detectOS()===
"Linux")if(window.navigator.userAgent.toLowerCase().indexOf("firefox")>-1)this.base("application/hwp-webpreview-plugin");else return;else $.browser.msie||~navigator.userAgent.search(/Trident/i)?this.base("clsid:E55C9850-D54F-4DF2-A7B4-B8C3B687BE2F"):this.base("application/hik-singlepreview-plugin");try{var a=location.href;a.indexOf("http://")==0?a=a.substring(7):a.indexOf("https://")==0&&(a=a.substring(8));console.log("57");var a=a.substring(0,a.indexOf("/")),b=this.ocxEl[0].AddSecuriteZone(a);console.log("58");
("false"==b||!1==b)&&jAlert(language.text("ocx.trustedSite"))}catch(c){}this.ocxEl[0].StopPreview()},addIndexCodeMap:function(a,b,c){c!=null&&(d[a]==null&&(d[a]=[]),d[a].push(c),e[c]=b)},removeIndexCodeMap:function(a){var b=d[a];if(b!=null){var c=null;b.length>0&&(c=b[b.length-1],b.pop());d[a].length<1&&(d[a]=null);c!=null&&(e[c]=null)}},getIndexCodeMap:function(a){return e[a]},SetVagServerInfo:function(a,b){this.ocxEl[0].SetVagServerInfo(a,b)},SetWindowId:function(a){this.ocxEl[0].SetWindowId(a)},
StartPreview:function(a){this.ocxEl[0].StartPreview(a)},StartPreviewEx:function(a){this.ocxEl[0].StartPreviewEx(a)},StopPreview:function(){this.ocxEl[0].StopPreview()},SetPerCfgInfo:function(a){this.ocxEl[0].SetPerCfgInfo(a)},SetToolBar:function(a){this.ocxEl[0].SetToolBar(a)},Set3DZoomMode:function(a){this.ocxEl[0].Set3DZoomMode(a)},SetVideoParam:function(a,b,c,d){this.ocxEl[0].SetVideoParam(a,b,c,d)},GetVideoParam:function(){return this.ocxEl[0].GetVideoParam()},SnapShot:function(a,b){this.ocxEl[0].SnapShot(a,
b)},StartRecord:function(){this.ocxEl[0].StartRecord()},OpenFolder:function(a){return this.ocxEl[0].OpenFolder(a)},OpenFile:function(a,b,c){return this.ocxEl[0].OpenFile(a,b,c)},SetRecordParam:function(a){this.ocxEl[0].SetRecordParam(a)},SetSnapParam:function(a){this.ocxEl[0].SetSnapParam(a)},SetOverLapMode:function(a){this.ocxEl[0].SetSnapParam(a)},SetAutoSize:function(a){this.ocxEl[0].SetAutoSize(a)},SetToken:function(a,b){this.ocxEl[0].SetToken(a,b)},SetEncrypt:function(a){this.ocxEl[0].SetEncrypt(a)},
SetToolBarAlwaysShow:function(a){this.ocxEl[0].SetToolBarAlwaysShow(a)},SetInstPlayCfg:function(a){this.ocxEl[0].SetInstPlayCfg(a)},SetRightCode:function(a){try{this.ocxEl[0].SetRightCode(a)}catch(b){}},SetSnapMultiType:function(a){try{this.ocxEl[0].SetSnapMultiType(a)}catch(b){}},SetDecode:function(a){try{this.ocxEl[0].SetDecode(a)}catch(b){}},PlaySound:function(a){try{this.ocxEl[0].PlaySound(a)}catch(b){}},EnterFishEye:function(){try{this.ocxEl[0].EnterFishEye()}catch(a){}},ExitFishEye:function(){try{this.ocxEl[0].ExitFishEye()}catch(a){}},
SetLayoutType:function(a){try{this.ocxEl[0].SetLayoutType(a)}catch(b){}},SetFishEyeParam:function(a){try{this.ocxEl[0].SetFishEyeParam(a)}catch(b){}},GetFishEyeParam:function(){try{return this.ocxEl[0].GetFishEyeParam()}catch(a){}},GetVersion:function(){try{return this.ocxEl[0].GetVersion()}catch(a){}},GetDirectoryPath:function(){try{var a=this.ocxEl[0].GetDirectoryPath();if(a=="null"||a==null)return null;if(a[a.length-1]=="\\")return a;return a+"\\"}catch(b){return null}},GetSystemDrive:function(){try{return this.ocxEl[0].GetSystemDrive()+
":"}catch(a){return"c:"}},GetUserDocument:function(){try{return this.ocxEl[0].GetUserDocument()}catch(a){return"C:\\Program Data"}},EnableMenu:function(a){try{this.ocxEl[0].EnableMenu(a)}catch(b){}},SetBarVisible:function(a){try{this.ocxEl[0].SetBarVisible(a)}catch(b){}},getOcxUrl:function(){return pt.ctx+"/web/softs/HIKOCX.CAB"},NotifyBSEvent:function(a){this.ocxEl[0].NotifyBSEvent(a)},checkFile:function(a){var b=null;window.XMLHttpRequest?b=new XMLHttpRequest:window.ActiveXObject&&(b=new ActiveXObject("Microsoft.XMLHTTP"));
if(b!=null){if(b.open("HEAD",a,!1),b.send(),b.readyState==4&&b.status==404)return!1}else jAlert(language.text("ocx.supportXmlHTTP"));return!0},handleException:function(){var a=this.checkFile(this.getOcxUrl()),b=this.msgEl||this.el;this.ocxEl!=null&&this.ocxEl.hide();b.find('div[msgType="msg"]').remove();b.find("*").hide();a?b.append('<div class="msg-b msg-b-stop"><i></i><div class="msg-cnt"><span>'+language.text("ocx.unload")+"</span></div></div>"):b.append('<div class="msg-b msg-b-stop"><i></i><div class="msg-cnt"><span>'+
language.text("ocx.unload")+"</span><p>"+language.text("ocx.nonExist")+"</p></div></div>");a&&this.msgEl&&this.msgEl.length>0&&(typeof currentIsDialog=="undefined"||currentIsDialog==!1)&&loader.show(language.text("ocx.loading"));return!1}})});
