define("./swf_schedule",["./active_x_swf"],function(t){var f=t("./active_x_swf");return f.extend({mode:3,version:2,num:7,maxBoard:4,useMinTimeCell:!1,minTimeCell:30,constructor:function(a){this.base(a,["hikui-schedule"],[{name:"mode",type:"int"},{name:"num",type:"int"},{name:"maxBoard",type:"int"},{name:"useMinTimeCell",type:"boolean"},{name:"minTimeCell",type:"int"}]);var d=this;d._resize=function(){d._value=d.getValue();d.width=d.el.width();d.height=d.el.height();$("#_flash_"+d.id).width(d.width)};
this.el.resize(d._resize)},alert:function(a){a=="copyUnSelect"?jAlert(language.text("shedule.copy"),language.text("dialog.info"),"attention"):a=="canDayDuplicated"?jAlert(language.text("shedule.special.error"),language.text("dialog.info"),"attention"):jAlert(language.text("shedule.delete"),language.text("dialog.info"),"attention")},setTypeColor:function(a,d){return this.findSWF().setTypeColor(a,d)},getLibPath:function(){return f.SWF_URL+"/schedule"},getBarVisibled:function(){return!1},getStyleName:function(){return"style_"+
(typeof pt!="undefined"?pt.lang||"zh_cn":"zh_cn")+".css"},init:function(){if(this.mode==1||this.mode==2)this.num=1;this.useMinTimeCell&&this.findSWF().setMinTimeCell(this.minTimeCell);var a="<data/>";try{a=this.findSWF().getValue()}catch(d){console.info("schedule getValue wrong:"+this._value)}this.setModleMode(this.mode,this.num);if(this._tirggerInit)try{a!=""&&a!="<data/>"?this.setValue(a):this.setValue(this._value)}catch(g){console.info("schedule setValue wrong:"+this._value)}else this.el.trigger("init",
this),this.trigger("init",this);this._tirggerInit=!0},render:function(){this.params={bgcolor:"#F7F9E8"};this.base(this.getLibPath()+"/main.swf?date="+new Date);if($.browser.msie&&this.ocxEl.attr("classid")==null)throw Error("no classid");},setModleMode:function(a,d){this.mode=a||this.mode;this.num=d||this.num;return this.findSWF().setModleMode(this.mode,this.num)},setValue:function(a){this._value=a;return this.findSWF().setValue(a)},btnHandle:function(a){a=this.findSWF().btnHandle(a);this._value=
this.findSWF().getValue();return a},getValue:function(){return this.findSWF().getValue()},setSpecialDayChecked:function(a){return this.findSWF().setSpecialDayChecked(a)},getCheckedDay:function(){return this.findSWF().getCheckedDay()},setStickStyle:function(a){return this.findSWF().setStickStyle(a)},selectTimes:function(a,d,g){function i(e){e=parseInt(e);if(e<10)return"0"+e;return e.toString()}function l(e,c){var b=e.split(":"),a=parseInt(b[0]),b=parseInt(b[1]);c==0?b==0?(a--,b=59):b--:c==1&&(b==59?
(a++,b=0):b++);return a+":"+b}function j(e){$("#startTime_value").text(e.cal.getNewDateStr());var c=b.endDp,a=c.cal,d=$("#startTime_value").text(),d=l(d,1);a.minDate=a.doCustomDate(d,d!=c.defMinDate?c.realFmt:c.realFullFmt,c.defMinDate);m=e.cal.date.H;n=e.cal.date.m;b._startSv("H",m);b._startSv("m",n)}function k(e){$("#endTime_value").text(e.cal.getNewDateStr());var c=b.startDp,a=c.cal,d=$("#endTime_value").text(),d=l(d,0);a.maxDate=a.doCustomDate(d,d!=c.defMaxDate?c.realFmt:c.realFullFmt,c.defMaxDate);
h=e.cal.date.H;o=e.cal.date.m;b._endSv("H",h);h==24?(b._endSv("m",0),b._endD.mI.disabled=!0):b._endD.mI.disabled=!1;b._endSv("m",o)}function p(){if(!(b==null||b._startSv==null)){b._startSv("H",m);b._startSv("m",n);var e=b.startDp.cal,c=b.startDp,a=f;e.minDate=e.doCustomDate(a,a!=c.defMinDate?c.realFmt:c.realFullFmt,c.defMinDate);j(c);b._endSv("H",h);h==24?(b._endSv("m",0),b._endD.mI.disabled=!0):b._endD.mI.disabled=!1;b._endSv("m",o);a=q;e=b.endDp.cal;c=b.endDp;k(c);e.maxDate=e.doCustomDate(a,a!=
c.defMaxDate?c.realFmt:c.realFullFmt,c.defMaxDate);b.startDp.cal.hideDDivChildren();b.endDp.cal.hideDDivChildren()}}this._selectId=this._selectId||{};this._selectId.id=a;var b=this,f=i(d/60)+":"+i(1*(d%60));$("#startTime_value").text(f);var m=parseInt(d/60),n=parseInt(1*(d%60)),q=i(g/60)+":"+i(1*(g%60));$("#endTime_value").text(q);var h=parseInt(g/60),o=parseInt(1*(g%60));if($("#schedule_time_select").data("dialog")!=null)p(),$("#schedule_time_select").dialog("open");else{seajs.use("{hikui}/calendar/wdatepicker",
function(a){b.useWdatepicker=!0;a(null,!0);$dp.$Text=function(a,b){if(this.el==null)return null;var c=$(a).text();return l(c,b)};var c=0;a({eCont:"startTime",el:"startTime",dateFmt:"HH:mm",maxDate:"#F{$dp.$Text('#endTime_value',0);}",alwaysUseStartDate:!0,notShowSS:!0,init:function(a,e,d){c++;b.startDp=a;b._startSv=d;c==2&&p()},autoShowQS:!1,onpicked:j,Hchanged:j,mchanged:j});a({eCont:"endTime",el:"endTime",dateFmt:"HH:mm",notShowSS:!0,minDate:"#F{$dp.$Text('#startTime_value',1);}",autoShowQS:!1,
init:function(a,e,d){c++;b.endDp=a;b._endSv=d;b._endD=e;c==2&&p()},schedule_24:!0,alwaysUseStartDate:!0,onpicked:k,Hchanged:k,mchanged:k})});var r=function(a){a.indexOf("0")==0&&(a=a.substring(1,2));return parseInt(a)},s=function(a){if(a.length<5)return 0;return r(a.substring(0,2))*60/1+r(a.substring(3,5))/1},b=this;$("#schedule_time_select").dialog({autoOpen:!0,modal:!0,width:450,height:400,buttons:[{text:language.text("dialog.ok"),"class":"bPrimary",click:function(){var a=$("#startTime_value").text();
if(a==""||a.length<5)jAlert(language.text("shedule.starttime.empty"),language.text("dialog.info"),"attention");else{var c=$("#endTime_value").text();if(c==""||c.length<5)jAlert(language.text("shedule.endtime.empty"),language.text("dialog.info"),"attention");else if(a=s(a),c=s(c),a<0)jAlert(language.text("shedule.starttime.invalid"),language.text("dialog.info"),"attention");else if(c>1440)jAlert(language.text("shedule.endtime.invalid"),language.text("dialog.info"),"attention");else if(a>=c)jAlert(language.text("shedule.time.error"),
language.text("dialog.info"),"attention");else{var d=b._selectId.id;b.findSWF().setTimeSelector(d,a,c)<0?jAlert(language.text("shedule.time.repeat"),language.text("dialog.info"),"attention"):(this.close(),$.sticky(language.text("shedule.config.sunccess"),{type:"ok"}))}}}},{text:language.text("dialog.close"),click:function(){this.close()}}]})}},destroy:function(){this.el.unbind("resize");this.useMinTimeCell&&($("#startTime").remove(),$("#endTime").remove());if(this.useWdatepicker&&(top.$("#_my97DP").remove(),
top.$dp=null,typeof $dp!="undefined"))$dp=null,top.$dp.hide(),top.$dp=null,top.$("#_my97DP").remove();return this.base()},getMaxBoard:function(){return this.maxBoard}})});
